// <auto-generated />
using System;
using AngularWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200311203814_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularWeb.Entities.Address.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasColumnName("addition")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Addition2")
                        .HasColumnName("addition2")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("AddressCompanyTypeId")
                        .HasColumnName("fk_address_company_type")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressCountryId")
                        .HasColumnName("fk_address_country")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("FAGBinaryId")
                        .HasColumnName("fk_logo")
                        .HasColumnType("bigint");

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnName("fk_parent_address")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnName("postcode")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Street")
                        .HasColumnName("street")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnName("timezone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("VatId")
                        .HasColumnName("vat_id_no")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressCompanyTypeId");

                    b.HasIndex("AddressCountryId");

                    b.HasIndex("FAGBinaryId");

                    b.HasIndex("ParentId");

                    b.ToTable("address_address");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPerson", b =>
                {
                    b.Property<long>("AddressPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .HasColumnName("department")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneOffice")
                        .HasColumnName("phone_office")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhonePrivate")
                        .HasColumnName("phone_private")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("PictureId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressPersonId");

                    b.HasIndex("PictureId");

                    b.ToTable("address_person");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPersonRelation", b =>
                {
                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("AddressPersonId")
                        .HasColumnType("bigint");

                    b.Property<long>("AddressPersonRelationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("AddressId", "AddressPersonId");

                    b.HasIndex("AddressPersonId");

                    b.ToTable("address_person_relation");
                });

            modelBuilder.Entity("AngularWeb.Entities.AddressCompanyType", b =>
                {
                    b.Property<long>("AddressCompanyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("AddressCompanyTypeId");

                    b.ToTable("address_company_type");
                });

            modelBuilder.Entity("AngularWeb.Entities.AddressCountry", b =>
                {
                    b.Property<long>("AddressCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressTextDeliveryScript")
                        .HasColumnName("address_text_delivery_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextDocumentScript")
                        .HasColumnName("address_text_document_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextInvoiceScript")
                        .HasColumnName("address_text_invoice_script")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("AdressType")
                        .HasColumnName("address_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<int>("EconomicArea")
                        .HasColumnName("economic_area")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Iso2cc")
                        .HasColumnName("iso_2cc")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Iso3cc")
                        .HasColumnName("iso_3cc")
                        .HasColumnType("varchar(3)");

                    b.Property<int>("IsoNumerical")
                        .HasColumnName("iso_numerical")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressCountryId");

                    b.ToTable("address_country");
                });

            modelBuilder.Entity("AngularWeb.Entities.Audit_WeatherForecast", b =>
                {
                    b.Property<long>("Audit_WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AuditUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("WeatherForecastId")
                        .HasColumnType("bigint");

                    b.HasKey("Audit_WeatherForecastId");

                    b.ToTable("Audit_WeatherForecast");
                });

            modelBuilder.Entity("AngularWeb.Entities.FAGBinary", b =>
                {
                    b.Property<long>("FAGBinaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Data")
                        .HasColumnName("data")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("FKId")
                        .HasColumnName("fk_id")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasColumnName("file_name")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("FAGBinaryId");

                    b.ToTable("fagBinarys");
                });

            modelBuilder.Entity("AngularWeb.Entities.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Yvette",
                            LastName = "Marquardt",
                            PasswordHash = new byte[] { 134, 32, 157, 161, 4, 13, 133, 88, 2, 105, 6, 59, 4, 3, 58, 219, 55, 117, 85, 47, 87, 193, 167, 242, 64, 211, 24, 88, 131, 12, 76, 220, 126, 36, 235, 157, 146, 54, 253, 201, 230, 254, 65, 17, 172, 212, 225, 106, 78, 158, 188, 111, 2, 175, 125, 43, 130, 43, 92, 218, 151, 1, 70, 255 },
                            PasswordSalt = new byte[] { 188, 141, 27, 128, 15, 243, 43, 212, 187, 13, 148, 52, 13, 194, 49, 72, 91, 194, 203, 214, 142, 127, 47, 177, 114, 46, 50, 149, 244, 225, 56, 203, 244, 47, 134, 18, 71, 187, 36, 69, 87, 252, 96, 126, 46, 53, 208, 134, 217, 97, 171, 81, 229, 227, 192, 8, 227, 228, 81, 95, 11, 12, 197, 103, 251, 153, 250, 36, 179, 156, 72, 255, 181, 192, 197, 58, 226, 253, 195, 76, 118, 75, 113, 147, 65, 133, 181, 134, 4, 177, 16, 197, 155, 178, 32, 32, 241, 156, 73, 149, 191, 232, 24, 66, 96, 222, 200, 223, 20, 25, 78, 141, 29, 169, 223, 181, 38, 198, 31, 158, 145, 157, 212, 3, 151, 101, 22, 144 },
                            Role = "Admin",
                            Username = "Nigel"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Joelle",
                            LastName = "Bergstrom",
                            PasswordHash = new byte[] { 134, 32, 157, 161, 4, 13, 133, 88, 2, 105, 6, 59, 4, 3, 58, 219, 55, 117, 85, 47, 87, 193, 167, 242, 64, 211, 24, 88, 131, 12, 76, 220, 126, 36, 235, 157, 146, 54, 253, 201, 230, 254, 65, 17, 172, 212, 225, 106, 78, 158, 188, 111, 2, 175, 125, 43, 130, 43, 92, 218, 151, 1, 70, 255 },
                            PasswordSalt = new byte[] { 188, 141, 27, 128, 15, 243, 43, 212, 187, 13, 148, 52, 13, 194, 49, 72, 91, 194, 203, 214, 142, 127, 47, 177, 114, 46, 50, 149, 244, 225, 56, 203, 244, 47, 134, 18, 71, 187, 36, 69, 87, 252, 96, 126, 46, 53, 208, 134, 217, 97, 171, 81, 229, 227, 192, 8, 227, 228, 81, 95, 11, 12, 197, 103, 251, 153, 250, 36, 179, 156, 72, 255, 181, 192, 197, 58, 226, 253, 195, 76, 118, 75, 113, 147, 65, 133, 181, 134, 4, 177, 16, 197, 155, 178, 32, 32, 241, 156, 73, 149, 191, 232, 24, 66, 96, 222, 200, 223, 20, 25, 78, 141, 29, 169, 223, 181, 38, 198, 31, 158, 145, 157, 212, 3, 151, 101, 22, 144 },
                            Role = "Admin",
                            Username = "Travis"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Madisyn",
                            LastName = "McCullough",
                            PasswordHash = new byte[] { 134, 32, 157, 161, 4, 13, 133, 88, 2, 105, 6, 59, 4, 3, 58, 219, 55, 117, 85, 47, 87, 193, 167, 242, 64, 211, 24, 88, 131, 12, 76, 220, 126, 36, 235, 157, 146, 54, 253, 201, 230, 254, 65, 17, 172, 212, 225, 106, 78, 158, 188, 111, 2, 175, 125, 43, 130, 43, 92, 218, 151, 1, 70, 255 },
                            PasswordSalt = new byte[] { 188, 141, 27, 128, 15, 243, 43, 212, 187, 13, 148, 52, 13, 194, 49, 72, 91, 194, 203, 214, 142, 127, 47, 177, 114, 46, 50, 149, 244, 225, 56, 203, 244, 47, 134, 18, 71, 187, 36, 69, 87, 252, 96, 126, 46, 53, 208, 134, 217, 97, 171, 81, 229, 227, 192, 8, 227, 228, 81, 95, 11, 12, 197, 103, 251, 153, 250, 36, 179, 156, 72, 255, 181, 192, 197, 58, 226, 253, 195, 76, 118, 75, 113, 147, 65, 133, 181, 134, 4, 177, 16, 197, 155, 178, 32, 32, 241, 156, 73, 149, 191, 232, 24, 66, 96, 222, 200, 223, 20, 25, 78, 141, 29, 169, 223, 181, 38, 198, 31, 158, 145, 157, 212, 3, 151, 101, 22, 144 },
                            Role = "Admin",
                            Username = "Coralie"
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Donna",
                            LastName = "Leannon",
                            PasswordHash = new byte[] { 134, 32, 157, 161, 4, 13, 133, 88, 2, 105, 6, 59, 4, 3, 58, 219, 55, 117, 85, 47, 87, 193, 167, 242, 64, 211, 24, 88, 131, 12, 76, 220, 126, 36, 235, 157, 146, 54, 253, 201, 230, 254, 65, 17, 172, 212, 225, 106, 78, 158, 188, 111, 2, 175, 125, 43, 130, 43, 92, 218, 151, 1, 70, 255 },
                            PasswordSalt = new byte[] { 188, 141, 27, 128, 15, 243, 43, 212, 187, 13, 148, 52, 13, 194, 49, 72, 91, 194, 203, 214, 142, 127, 47, 177, 114, 46, 50, 149, 244, 225, 56, 203, 244, 47, 134, 18, 71, 187, 36, 69, 87, 252, 96, 126, 46, 53, 208, 134, 217, 97, 171, 81, 229, 227, 192, 8, 227, 228, 81, 95, 11, 12, 197, 103, 251, 153, 250, 36, 179, 156, 72, 255, 181, 192, 197, 58, 226, 253, 195, 76, 118, 75, 113, 147, 65, 133, 181, 134, 4, 177, 16, 197, 155, 178, 32, 32, 241, 156, 73, 149, 191, 232, 24, 66, 96, 222, 200, 223, 20, 25, 78, 141, 29, 169, 223, 181, 38, 198, 31, 158, 145, 157, 212, 3, 151, 101, 22, 144 },
                            Role = "Admin",
                            Username = "Yesenia"
                        },
                        new
                        {
                            Id = 5L,
                            FirstName = "Sebastian",
                            LastName = "Schüler",
                            PasswordHash = new byte[] { 134, 32, 157, 161, 4, 13, 133, 88, 2, 105, 6, 59, 4, 3, 58, 219, 55, 117, 85, 47, 87, 193, 167, 242, 64, 211, 24, 88, 131, 12, 76, 220, 126, 36, 235, 157, 146, 54, 253, 201, 230, 254, 65, 17, 172, 212, 225, 106, 78, 158, 188, 111, 2, 175, 125, 43, 130, 43, 92, 218, 151, 1, 70, 255 },
                            PasswordSalt = new byte[] { 188, 141, 27, 128, 15, 243, 43, 212, 187, 13, 148, 52, 13, 194, 49, 72, 91, 194, 203, 214, 142, 127, 47, 177, 114, 46, 50, 149, 244, 225, 56, 203, 244, 47, 134, 18, 71, 187, 36, 69, 87, 252, 96, 126, 46, 53, 208, 134, 217, 97, 171, 81, 229, 227, 192, 8, 227, 228, 81, 95, 11, 12, 197, 103, 251, 153, 250, 36, 179, 156, 72, 255, 181, 192, 197, 58, 226, 253, 195, 76, 118, 75, 113, 147, 65, 133, 181, 134, 4, 177, 16, 197, 155, 178, 32, 32, 241, 156, 73, 149, 191, 232, 24, 66, 96, 222, 200, 223, 20, 25, 78, 141, 29, 169, 223, 181, 38, 198, 31, 158, 145, 157, 212, 3, 151, 101, 22, 144 },
                            Role = "Admin",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.Property<long>("WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasColumnName("summar_y")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("WeatherForecastId");

                    b.HasIndex("UserId");

                    b.ToTable("WeatherForecast");

                    b.HasData(
                        new
                        {
                            WeatherForecastId = 1L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 833, DateTimeKind.Utc).AddTicks(8393),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 12, 22, 13, 49, 27, 328, DateTimeKind.Local).AddTicks(1259),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 834, DateTimeKind.Utc).AddTicks(552),
                            ModifiedBy = 4L,
                            Summary = "Danish Krone",
                            TemperatureC = 15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 2L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 834, DateTimeKind.Utc).AddTicks(8374),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 11, 14, 20, 11, 8, 164, DateTimeKind.Local).AddTicks(6749),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 834, DateTimeKind.Utc).AddTicks(8423),
                            ModifiedBy = 5L,
                            Summary = "haptic",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 3L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(548),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 31, 0, 23, 10, 919, DateTimeKind.Local).AddTicks(916),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(554),
                            ModifiedBy = 5L,
                            Summary = "orchid",
                            TemperatureC = 5,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 4L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(2043),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 31, 16, 34, 0, 877, DateTimeKind.Local).AddTicks(7898),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(2048),
                            ModifiedBy = 1L,
                            Summary = "Practical",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 5L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(4061),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 20, 17, 30, 18, 231, DateTimeKind.Local).AddTicks(281),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(4066),
                            ModifiedBy = 3L,
                            Summary = "sexy",
                            TemperatureC = -14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 6L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(5568),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 4, 22, 40, 48, 979, DateTimeKind.Local).AddTicks(7412),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(5572),
                            ModifiedBy = 3L,
                            Summary = "even-keeled",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 7L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(7066),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 13, 9, 41, 34, 943, DateTimeKind.Local).AddTicks(1418),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 835, DateTimeKind.Utc).AddTicks(7071),
                            ModifiedBy = 3L,
                            Summary = "Fully-configurable",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 8L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 836, DateTimeKind.Utc).AddTicks(3667),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 8, 20, 0, 30, 902, DateTimeKind.Local).AddTicks(6399),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 836, DateTimeKind.Utc).AddTicks(3673),
                            ModifiedBy = 3L,
                            Summary = "Jewelery",
                            TemperatureC = -15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 9L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 836, DateTimeKind.Utc).AddTicks(6063),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 11, 21, 58, 31, 960, DateTimeKind.Local).AddTicks(6731),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 836, DateTimeKind.Utc).AddTicks(6068),
                            ModifiedBy = 3L,
                            Summary = "Mississippi",
                            TemperatureC = 8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 10L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 836, DateTimeKind.Utc).AddTicks(7676),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 5, 19, 17, 44, 3, 857, DateTimeKind.Local).AddTicks(5232),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 836, DateTimeKind.Utc).AddTicks(7681),
                            ModifiedBy = 5L,
                            Summary = "hard drive",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 11L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(1201),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 3, 12, 11, 52, 6, 474, DateTimeKind.Local).AddTicks(7612),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(1207),
                            ModifiedBy = 1L,
                            Summary = "Handmade Plastic Towels",
                            TemperatureC = -7,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 12L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3339),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 26, 19, 3, 27, 371, DateTimeKind.Local).AddTicks(996),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3344),
                            ModifiedBy = 1L,
                            Summary = "Assurance",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 13L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3418),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 15, 19, 9, 39, 735, DateTimeKind.Local).AddTicks(7371),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3420),
                            ModifiedBy = 5L,
                            Summary = "mobile",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 14L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3468),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 23, 6, 24, 40, 760, DateTimeKind.Local).AddTicks(1371),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3471),
                            ModifiedBy = 3L,
                            Summary = "Customer-focused",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 15L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3585),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 8, 8, 41, 3, 808, DateTimeKind.Local).AddTicks(5856),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(3588),
                            ModifiedBy = 1L,
                            Summary = "national",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 16L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(5006),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 12, 7, 3, 26, 11, 987, DateTimeKind.Local).AddTicks(1878),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(5010),
                            ModifiedBy = 4L,
                            Summary = "Planner",
                            TemperatureC = 14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 17L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(5072),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 18, 17, 25, 0, 375, DateTimeKind.Local).AddTicks(1092),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(5075),
                            ModifiedBy = 5L,
                            Summary = "open-source",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 18L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(6587),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 17, 0, 22, 23, 440, DateTimeKind.Local).AddTicks(4007),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(6591),
                            ModifiedBy = 3L,
                            Summary = "niches",
                            TemperatureC = -4,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 19L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(6656),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 10, 12, 12, 13, 10, 597, DateTimeKind.Local).AddTicks(6832),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(6659),
                            ModifiedBy = 4L,
                            Summary = "paradigms",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 20L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(8858),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 29, 23, 25, 35, 319, DateTimeKind.Local).AddTicks(3004),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 837, DateTimeKind.Utc).AddTicks(8863),
                            ModifiedBy = 4L,
                            Summary = "Kids, Electronics & Movies",
                            TemperatureC = 5,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 21L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(589),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 26, 2, 1, 15, 574, DateTimeKind.Local).AddTicks(5094),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(595),
                            ModifiedBy = 5L,
                            Summary = "reinvent",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 22L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(671),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 2, 1, 37, 52, 836, DateTimeKind.Local).AddTicks(8454),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(674),
                            ModifiedBy = 4L,
                            Summary = "Technician",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 23L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(2344),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 5, 8, 10, 25, 663, DateTimeKind.Local).AddTicks(6852),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(2348),
                            ModifiedBy = 1L,
                            Summary = "COM",
                            TemperatureC = -8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 24L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(3958),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 28, 4, 6, 29, 5, DateTimeKind.Local).AddTicks(9535),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(3962),
                            ModifiedBy = 3L,
                            Summary = "backing up",
                            TemperatureC = -13,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 25L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4030),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 10, 3, 21, 31, 807, DateTimeKind.Local).AddTicks(9985),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4033),
                            ModifiedBy = 3L,
                            Summary = "Delaware",
                            TemperatureC = -1,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 26L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4100),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 22, 14, 5, 59, 168, DateTimeKind.Local).AddTicks(746),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4102),
                            ModifiedBy = 5L,
                            Summary = "Practical Metal Hat",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 27L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4143),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 7, 23, 41, 57, 32, DateTimeKind.Local).AddTicks(4719),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4145),
                            ModifiedBy = 3L,
                            Summary = "1080p",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 28L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4187),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 8, 23, 22, 8, 40, 197, DateTimeKind.Local).AddTicks(4520),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(4189),
                            ModifiedBy = 1L,
                            Summary = "Self-enabling",
                            TemperatureC = 10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 29L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(5893),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 15, 1, 34, 47, 993, DateTimeKind.Local).AddTicks(5481),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(5898),
                            ModifiedBy = 3L,
                            Summary = "Credit Card Account",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 30L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(5962),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 4, 12, 19, 26, 27, 752, DateTimeKind.Local).AddTicks(1643),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(5965),
                            ModifiedBy = 1L,
                            Summary = "connecting",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 31L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(6108),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 2, 4, 29, 15, 104, DateTimeKind.Local).AddTicks(4143),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(6111),
                            ModifiedBy = 1L,
                            Summary = "Incredible Wooden Shoes",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 32L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(6802),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 17, 1, 6, 48, 361, DateTimeKind.Local).AddTicks(2683),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(6806),
                            ModifiedBy = 4L,
                            Summary = "Rustic Steel Pants",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 33L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8238),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 24, 9, 38, 22, 686, DateTimeKind.Local).AddTicks(3887),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8241),
                            ModifiedBy = 5L,
                            Summary = "Principal",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 34L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8306),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 25, 11, 12, 46, 3, DateTimeKind.Local).AddTicks(4592),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8309),
                            ModifiedBy = 2L,
                            Summary = "e-markets",
                            TemperatureC = -11,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 35L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8350),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 13, 22, 31, 32, 781, DateTimeKind.Local).AddTicks(2106),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8353),
                            ModifiedBy = 2L,
                            Summary = "efficient",
                            TemperatureC = -1,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 36L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8396),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 8, 4, 4, 33, 296, DateTimeKind.Local).AddTicks(5063),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8398),
                            ModifiedBy = 1L,
                            Summary = "Mobility",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 37L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8438),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 10, 11, 15, 4, 49, 32, DateTimeKind.Local).AddTicks(9286),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8441),
                            ModifiedBy = 3L,
                            Summary = "cyan",
                            TemperatureC = -4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 38L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8499),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 12, 8, 19, 44, 490, DateTimeKind.Local).AddTicks(1196),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8502),
                            ModifiedBy = 4L,
                            Summary = "Intelligent Concrete Shoes",
                            TemperatureC = 14,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 39L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8541),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 21, 19, 20, 28, 585, DateTimeKind.Local).AddTicks(1891),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8544),
                            ModifiedBy = 4L,
                            Summary = "calculating",
                            TemperatureC = 9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 40L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8583),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 11, 21, 11, 0, 670, DateTimeKind.Local).AddTicks(443),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(8585),
                            ModifiedBy = 2L,
                            Summary = "auxiliary",
                            TemperatureC = -10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 41L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9232),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 6, 19, 48, 315, DateTimeKind.Local).AddTicks(8625),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9236),
                            ModifiedBy = 4L,
                            Summary = "Metal",
                            TemperatureC = -1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 42L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9513),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 7, 17, 10, 59, 12, 927, DateTimeKind.Local).AddTicks(5627),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9516),
                            ModifiedBy = 5L,
                            Summary = "Baby, Beauty & Games",
                            TemperatureC = -4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 43L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9586),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 19, 13, 27, 17, 393, DateTimeKind.Local).AddTicks(9696),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9589),
                            ModifiedBy = 4L,
                            Summary = "Incredible Frozen Cheese",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 44L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9647),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 6, 11, 6, 3, 398, DateTimeKind.Local).AddTicks(8569),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 838, DateTimeKind.Utc).AddTicks(9650),
                            ModifiedBy = 5L,
                            Summary = "Tunisian Dinar",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 45L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1148),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 1, 6, 7, 1, 25, 440, DateTimeKind.Local).AddTicks(5916),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1152),
                            ModifiedBy = 2L,
                            Summary = "bypass",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 46L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1215),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 31, 12, 11, 0, 15, DateTimeKind.Local).AddTicks(555),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1303),
                            ModifiedBy = 3L,
                            Summary = "networks",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 47L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1351),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 15, 6, 5, 51, 97, DateTimeKind.Local).AddTicks(8852),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1354),
                            ModifiedBy = 4L,
                            Summary = "fuchsia",
                            TemperatureC = -3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 48L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1406),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 21, 17, 56, 28, 187, DateTimeKind.Local).AddTicks(6667),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(1409),
                            ModifiedBy = 5L,
                            Summary = "Brazilian Real",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 49L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(2995),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 27, 12, 40, 15, 78, DateTimeKind.Local).AddTicks(925),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(2999),
                            ModifiedBy = 2L,
                            Summary = "Trafficway",
                            TemperatureC = 15,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 50L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3062),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 18, 17, 12, 46, 25, DateTimeKind.Local).AddTicks(673),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3065),
                            ModifiedBy = 2L,
                            Summary = "Direct",
                            TemperatureC = 3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 51L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3106),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 21, 3, 32, 24, 785, DateTimeKind.Local).AddTicks(9322),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3109),
                            ModifiedBy = 5L,
                            Summary = "Implementation",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 52L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3146),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 5, 19, 37, 29, 157, DateTimeKind.Local).AddTicks(7850),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3148),
                            ModifiedBy = 4L,
                            Summary = "Brand",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 53L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3184),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 3, 19, 8, 6, 11, 784, DateTimeKind.Local).AddTicks(727),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3186),
                            ModifiedBy = 5L,
                            Summary = "Identity",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 54L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3222),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 24, 22, 51, 34, 650, DateTimeKind.Local).AddTicks(1745),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3225),
                            ModifiedBy = 5L,
                            Summary = "Internal",
                            TemperatureC = 11,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 55L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3273),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 18, 16, 1, 30, 631, DateTimeKind.Local).AddTicks(4992),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3276),
                            ModifiedBy = 4L,
                            Summary = "Guarani",
                            TemperatureC = -6,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 56L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3312),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 30, 14, 41, 10, 36, DateTimeKind.Local).AddTicks(7267),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3315),
                            ModifiedBy = 3L,
                            Summary = "Central",
                            TemperatureC = 8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 57L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3352),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 19, 7, 16, 30, 58, DateTimeKind.Local).AddTicks(1971),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3355),
                            ModifiedBy = 3L,
                            Summary = "online",
                            TemperatureC = 4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 58L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3391),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 3, 11, 19, 40, 15, 51, DateTimeKind.Local).AddTicks(1363),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3393),
                            ModifiedBy = 4L,
                            Summary = "index",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 59L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3431),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 2, 23, 24, 56, 607, DateTimeKind.Local).AddTicks(6739),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3433),
                            ModifiedBy = 1L,
                            Summary = "scale",
                            TemperatureC = -15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 60L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3470),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 16, 19, 22, 28, 301, DateTimeKind.Local).AddTicks(5888),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3473),
                            ModifiedBy = 2L,
                            Summary = "supply-chains",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 61L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3509),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 21, 23, 33, 5, 480, DateTimeKind.Local).AddTicks(3471),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3511),
                            ModifiedBy = 2L,
                            Summary = "SMS",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 62L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3547),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 23, 0, 40, 23, 750, DateTimeKind.Local).AddTicks(3822),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3549),
                            ModifiedBy = 2L,
                            Summary = "cultivate",
                            TemperatureC = -12,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 63L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3586),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 21, 12, 11, 28, 182, DateTimeKind.Local).AddTicks(7522),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3588),
                            ModifiedBy = 4L,
                            Summary = "Advanced",
                            TemperatureC = 14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 64L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3624),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 6, 30, 11, 16, 8, 788, DateTimeKind.Local).AddTicks(4477),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3627),
                            ModifiedBy = 2L,
                            Summary = "input",
                            TemperatureC = 1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 65L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3700),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 11, 12, 53, 1, 779, DateTimeKind.Local).AddTicks(9814),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3770),
                            ModifiedBy = 4L,
                            Summary = "Movies & Clothing",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 66L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3813),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 28, 2, 57, 23, 567, DateTimeKind.Local).AddTicks(4250),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3816),
                            ModifiedBy = 5L,
                            Summary = "Lead",
                            TemperatureC = 4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 67L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3855),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 16, 9, 14, 55, 595, DateTimeKind.Local).AddTicks(7711),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3857),
                            ModifiedBy = 3L,
                            Summary = "Agent",
                            TemperatureC = -12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 68L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3894),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 29, 21, 48, 38, 603, DateTimeKind.Local).AddTicks(4915),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3897),
                            ModifiedBy = 5L,
                            Summary = "real-time",
                            TemperatureC = 2,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 69L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3932),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 22, 4, 20, 195, DateTimeKind.Local).AddTicks(4514),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3935),
                            ModifiedBy = 3L,
                            Summary = "Corporate",
                            TemperatureC = -14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 70L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3989),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 9, 24, 9, 43, 12, 177, DateTimeKind.Local).AddTicks(7316),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(3992),
                            ModifiedBy = 5L,
                            Summary = "Small Cotton Car",
                            TemperatureC = -4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 71L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4027),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 16, 18, 15, 41, 561, DateTimeKind.Local).AddTicks(7581),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4029),
                            ModifiedBy = 4L,
                            Summary = "connecting",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 72L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4064),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 10, 2, 3, 50, 18, 287, DateTimeKind.Local).AddTicks(5082),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4067),
                            ModifiedBy = 5L,
                            Summary = "Gorgeous",
                            TemperatureC = -2,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 73L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4101),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 1, 11, 10, 58, 14, DateTimeKind.Local).AddTicks(7635),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4104),
                            ModifiedBy = 5L,
                            Summary = "scale",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 74L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4140),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 5, 31, 7, 2, 56, 547, DateTimeKind.Local).AddTicks(8218),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4143),
                            ModifiedBy = 5L,
                            Summary = "olive",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 75L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4179),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 4, 6, 4, 38, 50, 775, DateTimeKind.Local).AddTicks(7669),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4181),
                            ModifiedBy = 1L,
                            Summary = "Pre-emptive",
                            TemperatureC = -3,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 76L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4217),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 16, 7, 15, 21, 585, DateTimeKind.Local).AddTicks(9533),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4219),
                            ModifiedBy = 4L,
                            Summary = "Officer",
                            TemperatureC = 7,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 77L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4862),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 10, 20, 36, 15, 37, DateTimeKind.Local).AddTicks(816),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4865),
                            ModifiedBy = 2L,
                            Summary = "Square",
                            TemperatureC = 7,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 78L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4921),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 12, 29, 14, 2, 6, 970, DateTimeKind.Local).AddTicks(1746),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4923),
                            ModifiedBy = 1L,
                            Summary = "wireless",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 79L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4960),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 26, 3, 56, 2, 13, DateTimeKind.Local).AddTicks(2732),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(4963),
                            ModifiedBy = 1L,
                            Summary = "SMS",
                            TemperatureC = 4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 80L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5002),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 23, 15, 47, 37, 58, DateTimeKind.Local).AddTicks(7237),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5004),
                            ModifiedBy = 5L,
                            Summary = "Investment Account",
                            TemperatureC = 12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 81L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5041),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 7, 6, 12, 49, 424, DateTimeKind.Local).AddTicks(1288),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5044),
                            ModifiedBy = 5L,
                            Summary = "Maine",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 82L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5078),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 29, 21, 26, 0, 474, DateTimeKind.Local).AddTicks(214),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5080),
                            ModifiedBy = 2L,
                            Summary = "AI",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 83L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5116),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 27, 15, 15, 15, 844, DateTimeKind.Local).AddTicks(3590),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(5118),
                            ModifiedBy = 1L,
                            Summary = "open-source",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 84L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(6881),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 29, 19, 9, 13, 469, DateTimeKind.Local).AddTicks(7459),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(6886),
                            ModifiedBy = 5L,
                            Summary = "Berkshire",
                            TemperatureC = -11,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 85L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8526),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 9, 21, 38, 22, 553, DateTimeKind.Local).AddTicks(6220),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8531),
                            ModifiedBy = 4L,
                            Summary = "conglomeration",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 86L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8603),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 28, 21, 52, 9, 582, DateTimeKind.Local).AddTicks(3792),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8605),
                            ModifiedBy = 5L,
                            Summary = "Walks",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 87L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8647),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 6, 22, 25, 26, 406, DateTimeKind.Local).AddTicks(7580),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8650),
                            ModifiedBy = 5L,
                            Summary = "world-class",
                            TemperatureC = 15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 88L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8690),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 22, 13, 31, 12, 857, DateTimeKind.Local).AddTicks(1717),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8693),
                            ModifiedBy = 2L,
                            Summary = "Triple-buffered",
                            TemperatureC = 10,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 89L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8735),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 15, 0, 26, 5, 236, DateTimeKind.Local).AddTicks(238),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8738),
                            ModifiedBy = 5L,
                            Summary = "District",
                            TemperatureC = -13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 90L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8795),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 28, 16, 38, 49, 117, DateTimeKind.Local).AddTicks(9996),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8797),
                            ModifiedBy = 2L,
                            Summary = "Small Cotton Keyboard",
                            TemperatureC = 2,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 91L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8835),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 6, 5, 4, 40, 7, 616, DateTimeKind.Local).AddTicks(4917),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8837),
                            ModifiedBy = 5L,
                            Summary = "driver",
                            TemperatureC = -10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 92L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8873),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 25, 8, 0, 9, 820, DateTimeKind.Local).AddTicks(2397),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8875),
                            ModifiedBy = 2L,
                            Summary = "parse",
                            TemperatureC = 10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 93L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8921),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 31, 16, 40, 0, 883, DateTimeKind.Local).AddTicks(626),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8924),
                            ModifiedBy = 3L,
                            Summary = "Latvian Lats",
                            TemperatureC = -6,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 94L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8961),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 16, 18, 53, 1, 861, DateTimeKind.Local).AddTicks(5071),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(8963),
                            ModifiedBy = 4L,
                            Summary = "Centralized",
                            TemperatureC = 11,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 95L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(9001),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 11, 4, 55, 818, DateTimeKind.Local).AddTicks(2639),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(9003),
                            ModifiedBy = 4L,
                            Summary = "web-enabled",
                            TemperatureC = -12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 96L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(9040),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 25, 20, 45, 13, 241, DateTimeKind.Local).AddTicks(5829),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 839, DateTimeKind.Utc).AddTicks(9043),
                            ModifiedBy = 4L,
                            Summary = "Credit Card Account",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 97L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(448),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 10, 1, 58, 51, 706, DateTimeKind.Local).AddTicks(7470),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(451),
                            ModifiedBy = 4L,
                            Summary = "Cayman Islands",
                            TemperatureC = 13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 98L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(1832),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 8, 12, 23, 50, 38, 174, DateTimeKind.Local).AddTicks(7636),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(1838),
                            ModifiedBy = 2L,
                            Summary = "withdrawal",
                            TemperatureC = 8,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 99L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(1906),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 23, 12, 6, 55, 405, DateTimeKind.Local).AddTicks(9445),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(1909),
                            ModifiedBy = 4L,
                            Summary = "Response",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 100L,
                            Created = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(1968),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 6, 18, 45, 15, 652, DateTimeKind.Local).AddTicks(1455),
                            Modified = new DateTime(2020, 3, 11, 20, 38, 13, 840, DateTimeKind.Utc).AddTicks(1971),
                            ModifiedBy = 5L,
                            Summary = "Tasty Rubber Keyboard",
                            TemperatureC = 0,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.Address", b =>
                {
                    b.HasOne("AngularWeb.Entities.AddressCompanyType", "AddressCompanyType")
                        .WithMany()
                        .HasForeignKey("AddressCompanyTypeId");

                    b.HasOne("AngularWeb.Entities.AddressCountry", "AddressCountry")
                        .WithMany()
                        .HasForeignKey("AddressCountryId");

                    b.HasOne("AngularWeb.Entities.FAGBinary", "Logo")
                        .WithMany()
                        .HasForeignKey("FAGBinaryId");

                    b.HasOne("AngularWeb.Entities.Address.Address", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPerson", b =>
                {
                    b.HasOne("AngularWeb.Entities.FAGBinary", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPersonRelation", b =>
                {
                    b.HasOne("AngularWeb.Entities.Address.Address", "Address")
                        .WithMany("AddressPersonRelations")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AngularWeb.Entities.Address.AddressPerson", "AddressPerson")
                        .WithMany("AddressPersonRelations")
                        .HasForeignKey("AddressPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.HasOne("AngularWeb.Entities.User.User", "User")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
