// <auto-generated />
using System;
using AngularWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200311141459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularWeb.Entities.AddressCountry", b =>
                {
                    b.Property<long>("AddressCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressTextDeliveryScript")
                        .HasColumnName("address_text_delivery_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextDocumentScript")
                        .HasColumnName("address_text_document_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextInvoiceScript")
                        .HasColumnName("address_text_invoice_script")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("AdressType")
                        .HasColumnName("address_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<int>("EconomicArea")
                        .HasColumnName("economic_area")
                        .HasColumnType("int");

                    b.Property<string>("Iso2cc")
                        .HasColumnName("iso_2cc")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Iso3cc")
                        .HasColumnName("iso_3cc")
                        .HasColumnType("varchar(3)");

                    b.Property<int>("IsoNumerical")
                        .HasColumnName("iso_numerical")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressCountryId");

                    b.ToTable("address_country");
                });

            modelBuilder.Entity("AngularWeb.Entities.Audit_WeatherForecast", b =>
                {
                    b.Property<long>("Audit_WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AuditUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("WeatherForecastId")
                        .HasColumnType("bigint");

                    b.HasKey("Audit_WeatherForecastId");

                    b.ToTable("Audit_WeatherForecast");
                });

            modelBuilder.Entity("AngularWeb.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Yvette",
                            LastName = "Marquardt",
                            PasswordHash = new byte[] { 107, 143, 104, 163, 100, 71, 11, 205, 219, 160, 175, 144, 221, 230, 140, 113, 217, 156, 233, 240, 89, 122, 197, 250, 98, 136, 186, 52, 137, 170, 86, 179, 100, 24, 131, 228, 88, 174, 97, 63, 202, 56, 14, 83, 51, 214, 46, 185, 136, 172, 150, 119, 77, 144, 197, 45, 47, 52, 171, 227, 76, 80, 112, 80 },
                            PasswordSalt = new byte[] { 237, 94, 73, 227, 0, 65, 21, 243, 28, 71, 55, 61, 195, 15, 115, 32, 59, 12, 226, 183, 193, 238, 128, 199, 62, 58, 153, 133, 143, 64, 73, 237, 25, 123, 47, 196, 15, 156, 228, 228, 50, 205, 146, 150, 86, 216, 85, 7, 179, 155, 217, 86, 175, 145, 136, 102, 103, 251, 175, 221, 158, 131, 171, 133, 123, 211, 64, 8, 63, 124, 123, 155, 172, 8, 14, 2, 92, 255, 150, 189, 15, 132, 248, 181, 72, 245, 234, 168, 104, 36, 159, 27, 127, 157, 196, 131, 204, 36, 228, 212, 219, 189, 244, 5, 160, 129, 172, 141, 96, 242, 0, 182, 54, 56, 106, 6, 148, 52, 77, 119, 127, 20, 58, 137, 10, 223, 188, 209 },
                            Role = "Admin",
                            Username = "Nigel"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Joelle",
                            LastName = "Bergstrom",
                            PasswordHash = new byte[] { 107, 143, 104, 163, 100, 71, 11, 205, 219, 160, 175, 144, 221, 230, 140, 113, 217, 156, 233, 240, 89, 122, 197, 250, 98, 136, 186, 52, 137, 170, 86, 179, 100, 24, 131, 228, 88, 174, 97, 63, 202, 56, 14, 83, 51, 214, 46, 185, 136, 172, 150, 119, 77, 144, 197, 45, 47, 52, 171, 227, 76, 80, 112, 80 },
                            PasswordSalt = new byte[] { 237, 94, 73, 227, 0, 65, 21, 243, 28, 71, 55, 61, 195, 15, 115, 32, 59, 12, 226, 183, 193, 238, 128, 199, 62, 58, 153, 133, 143, 64, 73, 237, 25, 123, 47, 196, 15, 156, 228, 228, 50, 205, 146, 150, 86, 216, 85, 7, 179, 155, 217, 86, 175, 145, 136, 102, 103, 251, 175, 221, 158, 131, 171, 133, 123, 211, 64, 8, 63, 124, 123, 155, 172, 8, 14, 2, 92, 255, 150, 189, 15, 132, 248, 181, 72, 245, 234, 168, 104, 36, 159, 27, 127, 157, 196, 131, 204, 36, 228, 212, 219, 189, 244, 5, 160, 129, 172, 141, 96, 242, 0, 182, 54, 56, 106, 6, 148, 52, 77, 119, 127, 20, 58, 137, 10, 223, 188, 209 },
                            Role = "Admin",
                            Username = "Travis"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Madisyn",
                            LastName = "McCullough",
                            PasswordHash = new byte[] { 107, 143, 104, 163, 100, 71, 11, 205, 219, 160, 175, 144, 221, 230, 140, 113, 217, 156, 233, 240, 89, 122, 197, 250, 98, 136, 186, 52, 137, 170, 86, 179, 100, 24, 131, 228, 88, 174, 97, 63, 202, 56, 14, 83, 51, 214, 46, 185, 136, 172, 150, 119, 77, 144, 197, 45, 47, 52, 171, 227, 76, 80, 112, 80 },
                            PasswordSalt = new byte[] { 237, 94, 73, 227, 0, 65, 21, 243, 28, 71, 55, 61, 195, 15, 115, 32, 59, 12, 226, 183, 193, 238, 128, 199, 62, 58, 153, 133, 143, 64, 73, 237, 25, 123, 47, 196, 15, 156, 228, 228, 50, 205, 146, 150, 86, 216, 85, 7, 179, 155, 217, 86, 175, 145, 136, 102, 103, 251, 175, 221, 158, 131, 171, 133, 123, 211, 64, 8, 63, 124, 123, 155, 172, 8, 14, 2, 92, 255, 150, 189, 15, 132, 248, 181, 72, 245, 234, 168, 104, 36, 159, 27, 127, 157, 196, 131, 204, 36, 228, 212, 219, 189, 244, 5, 160, 129, 172, 141, 96, 242, 0, 182, 54, 56, 106, 6, 148, 52, 77, 119, 127, 20, 58, 137, 10, 223, 188, 209 },
                            Role = "Admin",
                            Username = "Coralie"
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Donna",
                            LastName = "Leannon",
                            PasswordHash = new byte[] { 107, 143, 104, 163, 100, 71, 11, 205, 219, 160, 175, 144, 221, 230, 140, 113, 217, 156, 233, 240, 89, 122, 197, 250, 98, 136, 186, 52, 137, 170, 86, 179, 100, 24, 131, 228, 88, 174, 97, 63, 202, 56, 14, 83, 51, 214, 46, 185, 136, 172, 150, 119, 77, 144, 197, 45, 47, 52, 171, 227, 76, 80, 112, 80 },
                            PasswordSalt = new byte[] { 237, 94, 73, 227, 0, 65, 21, 243, 28, 71, 55, 61, 195, 15, 115, 32, 59, 12, 226, 183, 193, 238, 128, 199, 62, 58, 153, 133, 143, 64, 73, 237, 25, 123, 47, 196, 15, 156, 228, 228, 50, 205, 146, 150, 86, 216, 85, 7, 179, 155, 217, 86, 175, 145, 136, 102, 103, 251, 175, 221, 158, 131, 171, 133, 123, 211, 64, 8, 63, 124, 123, 155, 172, 8, 14, 2, 92, 255, 150, 189, 15, 132, 248, 181, 72, 245, 234, 168, 104, 36, 159, 27, 127, 157, 196, 131, 204, 36, 228, 212, 219, 189, 244, 5, 160, 129, 172, 141, 96, 242, 0, 182, 54, 56, 106, 6, 148, 52, 77, 119, 127, 20, 58, 137, 10, 223, 188, 209 },
                            Role = "Admin",
                            Username = "Yesenia"
                        },
                        new
                        {
                            Id = 5L,
                            FirstName = "Sebastian",
                            LastName = "Schüler",
                            PasswordHash = new byte[] { 107, 143, 104, 163, 100, 71, 11, 205, 219, 160, 175, 144, 221, 230, 140, 113, 217, 156, 233, 240, 89, 122, 197, 250, 98, 136, 186, 52, 137, 170, 86, 179, 100, 24, 131, 228, 88, 174, 97, 63, 202, 56, 14, 83, 51, 214, 46, 185, 136, 172, 150, 119, 77, 144, 197, 45, 47, 52, 171, 227, 76, 80, 112, 80 },
                            PasswordSalt = new byte[] { 237, 94, 73, 227, 0, 65, 21, 243, 28, 71, 55, 61, 195, 15, 115, 32, 59, 12, 226, 183, 193, 238, 128, 199, 62, 58, 153, 133, 143, 64, 73, 237, 25, 123, 47, 196, 15, 156, 228, 228, 50, 205, 146, 150, 86, 216, 85, 7, 179, 155, 217, 86, 175, 145, 136, 102, 103, 251, 175, 221, 158, 131, 171, 133, 123, 211, 64, 8, 63, 124, 123, 155, 172, 8, 14, 2, 92, 255, 150, 189, 15, 132, 248, 181, 72, 245, 234, 168, 104, 36, 159, 27, 127, 157, 196, 131, 204, 36, 228, 212, 219, 189, 244, 5, 160, 129, 172, 141, 96, 242, 0, 182, 54, 56, 106, 6, 148, 52, 77, 119, 127, 20, 58, 137, 10, 223, 188, 209 },
                            Role = "Admin",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.Property<long>("WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasColumnName("summar_y")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("WeatherForecastId");

                    b.HasIndex("UserId");

                    b.ToTable("WeatherForecast");

                    b.HasData(
                        new
                        {
                            WeatherForecastId = 1L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 735, DateTimeKind.Utc).AddTicks(1688),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 12, 22, 7, 26, 12, 228, DateTimeKind.Local).AddTicks(4887),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 735, DateTimeKind.Utc).AddTicks(4433),
                            ModifiedBy = 4L,
                            Summary = "Danish Krone",
                            TemperatureC = 15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 2L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 736, DateTimeKind.Utc).AddTicks(4995),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 11, 14, 13, 47, 53, 66, DateTimeKind.Local).AddTicks(3307),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 736, DateTimeKind.Utc).AddTicks(5063),
                            ModifiedBy = 5L,
                            Summary = "haptic",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 3L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 736, DateTimeKind.Utc).AddTicks(8277),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 30, 17, 59, 55, 820, DateTimeKind.Local).AddTicks(8597),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 736, DateTimeKind.Utc).AddTicks(8292),
                            ModifiedBy = 5L,
                            Summary = "orchid",
                            TemperatureC = 5,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 4L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 737, DateTimeKind.Utc).AddTicks(1468),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 31, 10, 10, 45, 779, DateTimeKind.Local).AddTicks(7283),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 737, DateTimeKind.Utc).AddTicks(1478),
                            ModifiedBy = 1L,
                            Summary = "Practical",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 5L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 737, DateTimeKind.Utc).AddTicks(5708),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 20, 11, 7, 3, 133, DateTimeKind.Local).AddTicks(1881),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 737, DateTimeKind.Utc).AddTicks(5717),
                            ModifiedBy = 3L,
                            Summary = "sexy",
                            TemperatureC = -14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 6L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 737, DateTimeKind.Utc).AddTicks(9233),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 4, 16, 17, 33, 882, DateTimeKind.Local).AddTicks(994),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 737, DateTimeKind.Utc).AddTicks(9249),
                            ModifiedBy = 3L,
                            Summary = "even-keeled",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 7L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 738, DateTimeKind.Utc).AddTicks(3165),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 13, 3, 18, 19, 845, DateTimeKind.Local).AddTicks(7492),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 738, DateTimeKind.Utc).AddTicks(3171),
                            ModifiedBy = 3L,
                            Summary = "Fully-configurable",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 8L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 739, DateTimeKind.Utc).AddTicks(1855),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 8, 13, 37, 15, 805, DateTimeKind.Local).AddTicks(4566),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 739, DateTimeKind.Utc).AddTicks(1863),
                            ModifiedBy = 3L,
                            Summary = "Jewelery",
                            TemperatureC = -15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 9L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 739, DateTimeKind.Utc).AddTicks(4909),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 11, 15, 35, 16, 863, DateTimeKind.Local).AddTicks(5563),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 739, DateTimeKind.Utc).AddTicks(4916),
                            ModifiedBy = 3L,
                            Summary = "Mississippi",
                            TemperatureC = 8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 10L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 739, DateTimeKind.Utc).AddTicks(7023),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 5, 19, 11, 20, 48, 760, DateTimeKind.Local).AddTicks(4533),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 739, DateTimeKind.Utc).AddTicks(7030),
                            ModifiedBy = 5L,
                            Summary = "hard drive",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 11L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(1613),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 3, 12, 5, 28, 51, 377, DateTimeKind.Local).AddTicks(8009),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(1620),
                            ModifiedBy = 1L,
                            Summary = "Handmade Plastic Towels",
                            TemperatureC = -7,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 12L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4232),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 26, 12, 40, 12, 274, DateTimeKind.Local).AddTicks(1876),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4238),
                            ModifiedBy = 1L,
                            Summary = "Assurance",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 13L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4340),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 15, 12, 46, 24, 638, DateTimeKind.Local).AddTicks(8290),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4344),
                            ModifiedBy = 5L,
                            Summary = "mobile",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 14L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4407),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 23, 0, 1, 25, 663, DateTimeKind.Local).AddTicks(2307),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4411),
                            ModifiedBy = 3L,
                            Summary = "Customer-focused",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 15L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4464),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 8, 2, 17, 48, 711, DateTimeKind.Local).AddTicks(6733),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(4467),
                            ModifiedBy = 1L,
                            Summary = "national",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 16L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(6362),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 12, 6, 21, 2, 56, 890, DateTimeKind.Local).AddTicks(3218),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(6367),
                            ModifiedBy = 4L,
                            Summary = "Planner",
                            TemperatureC = 14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 17L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(6457),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 18, 11, 1, 45, 278, DateTimeKind.Local).AddTicks(2473),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(6461),
                            ModifiedBy = 5L,
                            Summary = "open-source",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 18L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(8676),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 16, 17, 59, 8, 343, DateTimeKind.Local).AddTicks(6085),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(8682),
                            ModifiedBy = 3L,
                            Summary = "niches",
                            TemperatureC = -4,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 19L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(8769),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 10, 12, 5, 49, 55, 500, DateTimeKind.Local).AddTicks(8940),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 740, DateTimeKind.Utc).AddTicks(8772),
                            ModifiedBy = 4L,
                            Summary = "paradigms",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 20L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(2033),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 29, 17, 2, 20, 222, DateTimeKind.Local).AddTicks(6163),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(2039),
                            ModifiedBy = 4L,
                            Summary = "Kids, Electronics & Movies",
                            TemperatureC = 5,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 21L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(4436),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 25, 19, 38, 0, 477, DateTimeKind.Local).AddTicks(8928),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(4442),
                            ModifiedBy = 5L,
                            Summary = "reinvent",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 22L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(4548),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 1, 19, 14, 37, 740, DateTimeKind.Local).AddTicks(2326),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(4552),
                            ModifiedBy = 4L,
                            Summary = "Technician",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 23L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(6558),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 5, 1, 47, 10, 567, DateTimeKind.Local).AddTicks(1054),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(6564),
                            ModifiedBy = 1L,
                            Summary = "COM",
                            TemperatureC = -8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 24L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8749),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 27, 21, 43, 13, 909, DateTimeKind.Local).AddTicks(4314),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8755),
                            ModifiedBy = 3L,
                            Summary = "backing up",
                            TemperatureC = -13,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 25L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8848),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 9, 20, 58, 16, 711, DateTimeKind.Local).AddTicks(4800),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8852),
                            ModifiedBy = 3L,
                            Summary = "Delaware",
                            TemperatureC = -1,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 26L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8940),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 22, 7, 42, 44, 71, DateTimeKind.Local).AddTicks(5583),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8944),
                            ModifiedBy = 5L,
                            Summary = "Practical Metal Hat",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 27L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(8996),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 7, 17, 18, 41, 935, DateTimeKind.Local).AddTicks(9570),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(9000),
                            ModifiedBy = 3L,
                            Summary = "1080p",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 28L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(9051),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 8, 23, 15, 45, 25, 100, DateTimeKind.Local).AddTicks(9382),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 741, DateTimeKind.Utc).AddTicks(9055),
                            ModifiedBy = 1L,
                            Summary = "Self-enabling",
                            TemperatureC = 10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 29L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(1294),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 14, 19, 11, 32, 897, DateTimeKind.Local).AddTicks(870),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(1299),
                            ModifiedBy = 3L,
                            Summary = "Credit Card Account",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 30L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(1385),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 4, 12, 13, 3, 12, 655, DateTimeKind.Local).AddTicks(7063),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(1388),
                            ModifiedBy = 1L,
                            Summary = "connecting",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 31L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(1470),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 1, 22, 6, 0, 7, DateTimeKind.Local).AddTicks(9505),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(1473),
                            ModifiedBy = 1L,
                            Summary = "Incredible Wooden Shoes",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 32L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(2363),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 16, 18, 43, 33, 264, DateTimeKind.Local).AddTicks(8234),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(2368),
                            ModifiedBy = 4L,
                            Summary = "Rustic Steel Pants",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 33L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4255),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 24, 3, 15, 7, 589, DateTimeKind.Local).AddTicks(9892),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4260),
                            ModifiedBy = 5L,
                            Summary = "Principal",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 34L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4348),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 25, 4, 49, 30, 907, DateTimeKind.Local).AddTicks(631),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4352),
                            ModifiedBy = 2L,
                            Summary = "e-markets",
                            TemperatureC = -11,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 35L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4406),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 13, 16, 8, 17, 684, DateTimeKind.Local).AddTicks(8159),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4409),
                            ModifiedBy = 2L,
                            Summary = "efficient",
                            TemperatureC = -1,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 36L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4463),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 7, 21, 41, 18, 200, DateTimeKind.Local).AddTicks(1127),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4466),
                            ModifiedBy = 1L,
                            Summary = "Mobility",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 37L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4517),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 10, 11, 8, 41, 33, 936, DateTimeKind.Local).AddTicks(5363),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4521),
                            ModifiedBy = 3L,
                            Summary = "cyan",
                            TemperatureC = -4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 38L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4592),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 12, 1, 56, 29, 393, DateTimeKind.Local).AddTicks(7286),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4595),
                            ModifiedBy = 4L,
                            Summary = "Intelligent Concrete Shoes",
                            TemperatureC = 14,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 39L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4644),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 21, 12, 57, 13, 488, DateTimeKind.Local).AddTicks(7991),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4648),
                            ModifiedBy = 4L,
                            Summary = "calculating",
                            TemperatureC = 9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 40L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4801),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 11, 14, 47, 45, 573, DateTimeKind.Local).AddTicks(6657),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(4805),
                            ModifiedBy = 2L,
                            Summary = "auxiliary",
                            TemperatureC = -10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 41L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(5667),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 6, 23, 56, 33, 219, DateTimeKind.Local).AddTicks(5051),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(5671),
                            ModifiedBy = 4L,
                            Summary = "Metal",
                            TemperatureC = -1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 42L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(6071),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 7, 17, 4, 35, 57, 831, DateTimeKind.Local).AddTicks(2178),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(6075),
                            ModifiedBy = 5L,
                            Summary = "Baby, Beauty & Games",
                            TemperatureC = -4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 43L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(6162),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 19, 7, 4, 2, 297, DateTimeKind.Local).AddTicks(6267),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(6166),
                            ModifiedBy = 4L,
                            Summary = "Incredible Frozen Cheese",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 44L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(6236),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 6, 4, 42, 48, 302, DateTimeKind.Local).AddTicks(5154),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(6239),
                            ModifiedBy = 5L,
                            Summary = "Tunisian Dinar",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 45L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8551),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 1, 6, 0, 38, 10, 344, DateTimeKind.Local).AddTicks(3303),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8556),
                            ModifiedBy = 2L,
                            Summary = "bypass",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 46L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8651),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 31, 5, 47, 44, 918, DateTimeKind.Local).AddTicks(7984),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8654),
                            ModifiedBy = 3L,
                            Summary = "networks",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 47L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8709),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 14, 23, 42, 36, 1, DateTimeKind.Local).AddTicks(6207),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8712),
                            ModifiedBy = 4L,
                            Summary = "fuchsia",
                            TemperatureC = -3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 48L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8779),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 21, 11, 33, 13, 91, DateTimeKind.Local).AddTicks(4038),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 742, DateTimeKind.Utc).AddTicks(8783),
                            ModifiedBy = 5L,
                            Summary = "Brazilian Real",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 49L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(709),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 27, 6, 16, 59, 981, DateTimeKind.Local).AddTicks(8626),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(714),
                            ModifiedBy = 2L,
                            Summary = "Trafficway",
                            TemperatureC = 15,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 50L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(809),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 18, 10, 49, 30, 928, DateTimeKind.Local).AddTicks(8416),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(814),
                            ModifiedBy = 2L,
                            Summary = "Direct",
                            TemperatureC = 3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 51L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(869),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 20, 21, 9, 9, 689, DateTimeKind.Local).AddTicks(7079),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(873),
                            ModifiedBy = 5L,
                            Summary = "Implementation",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 52L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(922),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 5, 13, 14, 14, 61, DateTimeKind.Local).AddTicks(5621),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(925),
                            ModifiedBy = 4L,
                            Summary = "Brand",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 53L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(974),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 3, 19, 1, 42, 56, 687, DateTimeKind.Local).AddTicks(8511),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(977),
                            ModifiedBy = 5L,
                            Summary = "Identity",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 54L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1028),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 24, 16, 28, 19, 553, DateTimeKind.Local).AddTicks(9546),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1031),
                            ModifiedBy = 5L,
                            Summary = "Internal",
                            TemperatureC = 11,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 55L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1195),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 18, 9, 38, 15, 535, DateTimeKind.Local).AddTicks(2811),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1199),
                            ModifiedBy = 4L,
                            Summary = "Guarani",
                            TemperatureC = -6,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 56L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1256),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 30, 8, 17, 54, 940, DateTimeKind.Local).AddTicks(5204),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1259),
                            ModifiedBy = 3L,
                            Summary = "Central",
                            TemperatureC = 8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 57L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1310),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 19, 0, 53, 14, 961, DateTimeKind.Local).AddTicks(9924),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1313),
                            ModifiedBy = 3L,
                            Summary = "online",
                            TemperatureC = 4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 58L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1362),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 3, 11, 13, 16, 59, 954, DateTimeKind.Local).AddTicks(9330),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1365),
                            ModifiedBy = 4L,
                            Summary = "index",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 59L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1420),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 2, 17, 1, 41, 511, DateTimeKind.Local).AddTicks(4722),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1423),
                            ModifiedBy = 1L,
                            Summary = "scale",
                            TemperatureC = -15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 60L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1473),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 16, 12, 59, 13, 205, DateTimeKind.Local).AddTicks(3887),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1477),
                            ModifiedBy = 2L,
                            Summary = "supply-chains",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 61L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1528),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 21, 17, 9, 50, 384, DateTimeKind.Local).AddTicks(1485),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1532),
                            ModifiedBy = 2L,
                            Summary = "SMS",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 62L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1580),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 22, 18, 17, 8, 654, DateTimeKind.Local).AddTicks(1851),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1584),
                            ModifiedBy = 2L,
                            Summary = "cultivate",
                            TemperatureC = -12,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 63L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1635),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 21, 5, 48, 13, 86, DateTimeKind.Local).AddTicks(5566),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1638),
                            ModifiedBy = 4L,
                            Summary = "Advanced",
                            TemperatureC = 14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 64L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1686),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 6, 30, 4, 52, 53, 692, DateTimeKind.Local).AddTicks(2534),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1690),
                            ModifiedBy = 2L,
                            Summary = "input",
                            TemperatureC = 1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 65L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1792),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 11, 6, 29, 46, 683, DateTimeKind.Local).AddTicks(7903),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1796),
                            ModifiedBy = 4L,
                            Summary = "Movies & Clothing",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 66L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1846),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 27, 20, 34, 8, 471, DateTimeKind.Local).AddTicks(2280),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1850),
                            ModifiedBy = 5L,
                            Summary = "Lead",
                            TemperatureC = 4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 67L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1904),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 16, 2, 51, 40, 499, DateTimeKind.Local).AddTicks(5756),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1908),
                            ModifiedBy = 3L,
                            Summary = "Agent",
                            TemperatureC = -12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 68L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1960),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 29, 15, 25, 23, 507, DateTimeKind.Local).AddTicks(2975),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(1963),
                            ModifiedBy = 5L,
                            Summary = "real-time",
                            TemperatureC = 2,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 69L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2011),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 15, 41, 5, 99, DateTimeKind.Local).AddTicks(2588),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2015),
                            ModifiedBy = 3L,
                            Summary = "Corporate",
                            TemperatureC = -14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 70L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2087),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 9, 24, 3, 19, 57, 81, DateTimeKind.Local).AddTicks(5410),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2091),
                            ModifiedBy = 5L,
                            Summary = "Small Cotton Car",
                            TemperatureC = -4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 71L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2139),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 16, 11, 52, 26, 465, DateTimeKind.Local).AddTicks(5688),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2142),
                            ModifiedBy = 4L,
                            Summary = "connecting",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 72L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2190),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 10, 1, 21, 27, 3, 191, DateTimeKind.Local).AddTicks(3204),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2194),
                            ModifiedBy = 5L,
                            Summary = "Gorgeous",
                            TemperatureC = -2,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 73L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2240),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 1, 4, 47, 42, 918, DateTimeKind.Local).AddTicks(5770),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2244),
                            ModifiedBy = 5L,
                            Summary = "scale",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 74L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2293),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 5, 31, 0, 39, 41, 451, DateTimeKind.Local).AddTicks(6366),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2296),
                            ModifiedBy = 5L,
                            Summary = "olive",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 75L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2433),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 4, 5, 22, 15, 35, 679, DateTimeKind.Local).AddTicks(5917),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2436),
                            ModifiedBy = 1L,
                            Summary = "Pre-emptive",
                            TemperatureC = -3,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 76L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2490),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 16, 0, 52, 6, 489, DateTimeKind.Local).AddTicks(7802),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(2494),
                            ModifiedBy = 4L,
                            Summary = "Officer",
                            TemperatureC = 7,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 77L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3388),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 10, 14, 12, 59, 940, DateTimeKind.Local).AddTicks(9329),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3393),
                            ModifiedBy = 2L,
                            Summary = "Square",
                            TemperatureC = 7,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 78L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3468),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 12, 29, 7, 38, 51, 874, DateTimeKind.Local).AddTicks(291),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3473),
                            ModifiedBy = 1L,
                            Summary = "wireless",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 79L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3522),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 21, 32, 46, 917, DateTimeKind.Local).AddTicks(1289),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3525),
                            ModifiedBy = 1L,
                            Summary = "SMS",
                            TemperatureC = 4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 80L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3578),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 23, 9, 24, 21, 962, DateTimeKind.Local).AddTicks(5810),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3582),
                            ModifiedBy = 5L,
                            Summary = "Investment Account",
                            TemperatureC = 12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 81L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3633),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 6, 23, 49, 34, 327, DateTimeKind.Local).AddTicks(9876),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3637),
                            ModifiedBy = 5L,
                            Summary = "Maine",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 82L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3684),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 29, 15, 2, 45, 377, DateTimeKind.Local).AddTicks(8816),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3687),
                            ModifiedBy = 2L,
                            Summary = "AI",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 83L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3735),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 27, 8, 52, 0, 748, DateTimeKind.Local).AddTicks(2205),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(3738),
                            ModifiedBy = 1L,
                            Summary = "open-source",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 84L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(5593),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 29, 12, 45, 58, 373, DateTimeKind.Local).AddTicks(6169),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(5599),
                            ModifiedBy = 5L,
                            Summary = "Berkshire",
                            TemperatureC = -11,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 85L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7655),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 9, 15, 15, 7, 457, DateTimeKind.Local).AddTicks(5337),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7660),
                            ModifiedBy = 4L,
                            Summary = "conglomeration",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 86L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7751),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 28, 15, 28, 54, 486, DateTimeKind.Local).AddTicks(2938),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7755),
                            ModifiedBy = 5L,
                            Summary = "Walks",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 87L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7808),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 6, 16, 2, 11, 310, DateTimeKind.Local).AddTicks(6739),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7812),
                            ModifiedBy = 5L,
                            Summary = "world-class",
                            TemperatureC = 15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 88L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7860),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 22, 7, 7, 57, 761, DateTimeKind.Local).AddTicks(884),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7864),
                            ModifiedBy = 2L,
                            Summary = "Triple-buffered",
                            TemperatureC = 10,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 89L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7917),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 14, 18, 2, 50, 139, DateTimeKind.Local).AddTicks(9417),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7920),
                            ModifiedBy = 5L,
                            Summary = "District",
                            TemperatureC = -13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 90L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7992),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 28, 10, 15, 34, 21, DateTimeKind.Local).AddTicks(9190),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(7995),
                            ModifiedBy = 2L,
                            Summary = "Small Cotton Keyboard",
                            TemperatureC = 2,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 91L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8049),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 6, 4, 22, 16, 52, 520, DateTimeKind.Local).AddTicks(4128),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8053),
                            ModifiedBy = 5L,
                            Summary = "driver",
                            TemperatureC = -10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 92L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8101),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 25, 1, 36, 54, 724, DateTimeKind.Local).AddTicks(1621),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8104),
                            ModifiedBy = 2L,
                            Summary = "parse",
                            TemperatureC = 10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 93L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8164),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 31, 10, 16, 45, 786, DateTimeKind.Local).AddTicks(9866),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8168),
                            ModifiedBy = 3L,
                            Summary = "Latvian Lats",
                            TemperatureC = -6,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 94L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8216),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 16, 12, 29, 46, 765, DateTimeKind.Local).AddTicks(4322),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8219),
                            ModifiedBy = 4L,
                            Summary = "Centralized",
                            TemperatureC = 11,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 95L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8466),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 4, 41, 40, 722, DateTimeKind.Local).AddTicks(2095),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8470),
                            ModifiedBy = 4L,
                            Summary = "web-enabled",
                            TemperatureC = -12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 96L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8527),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 25, 14, 21, 58, 145, DateTimeKind.Local).AddTicks(5312),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 743, DateTimeKind.Utc).AddTicks(8530),
                            ModifiedBy = 4L,
                            Summary = "Credit Card Account",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 97L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(411),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 9, 19, 35, 36, 610, DateTimeKind.Local).AddTicks(7423),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(416),
                            ModifiedBy = 4L,
                            Summary = "Cayman Islands",
                            TemperatureC = 13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 98L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(2292),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 8, 12, 17, 27, 23, 78, DateTimeKind.Local).AddTicks(8082),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(2298),
                            ModifiedBy = 2L,
                            Summary = "withdrawal",
                            TemperatureC = 8,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 99L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(2386),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 23, 5, 43, 40, 309, DateTimeKind.Local).AddTicks(9922),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(2390),
                            ModifiedBy = 4L,
                            Summary = "Response",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 100L,
                            Created = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(2466),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 6, 12, 22, 0, 556, DateTimeKind.Local).AddTicks(1950),
                            Modified = new DateTime(2020, 3, 11, 14, 14, 58, 744, DateTimeKind.Utc).AddTicks(2469),
                            ModifiedBy = 5L,
                            Summary = "Tasty Rubber Keyboard",
                            TemperatureC = 0,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.HasOne("AngularWeb.Entities.User", "User")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
