// <auto-generated />
using System;
using AngularWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200310140223_Initial_01")]
    partial class Initial_01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularWeb.Entities.Audit_WeatherForecast", b =>
                {
                    b.Property<Guid>("Audit_WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AuditUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<Guid>("WeatherForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Audit_WeatherForecastId");

                    b.ToTable("Audit_WeatherForecast");
                });

            modelBuilder.Entity("AngularWeb.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21a56184-0170-4d04-9280-0a57729a62d5"),
                            FirstName = "Yvette",
                            LastName = "Marquardt",
                            PasswordHash = new byte[] { 187, 8, 62, 31, 109, 23, 231, 120, 220, 222, 102, 28, 199, 220, 180, 42, 35, 243, 63, 45, 161, 155, 19, 169, 230, 163, 248, 141, 109, 44, 240, 189, 44, 136, 53, 89, 148, 250, 225, 95, 244, 231, 24, 39, 51, 185, 230, 54, 23, 48, 104, 84, 188, 99, 164, 206, 230, 16, 21, 38, 141, 199, 9, 77 },
                            PasswordSalt = new byte[] { 39, 241, 206, 221, 77, 230, 37, 254, 141, 35, 127, 234, 59, 30, 60, 191, 186, 46, 222, 64, 121, 239, 211, 122, 28, 124, 122, 150, 206, 39, 1, 242, 250, 19, 183, 56, 133, 99, 178, 101, 233, 60, 70, 223, 43, 33, 77, 50, 230, 141, 230, 69, 157, 125, 70, 142, 5, 43, 44, 183, 246, 29, 109, 54, 184, 220, 108, 230, 215, 191, 222, 229, 81, 202, 190, 178, 15, 216, 153, 165, 85, 55, 241, 254, 228, 149, 223, 158, 55, 170, 220, 134, 139, 104, 51, 228, 148, 162, 141, 74, 177, 187, 171, 76, 155, 13, 33, 226, 83, 131, 91, 165, 35, 41, 146, 145, 17, 29, 251, 72, 68, 192, 43, 17, 160, 130, 136, 188 },
                            Role = "Admin",
                            Username = "Nigel"
                        },
                        new
                        {
                            Id = new Guid("c3099f2d-6dcb-4608-9b35-4270abc2dff7"),
                            FirstName = "Joelle",
                            LastName = "Bergstrom",
                            PasswordHash = new byte[] { 187, 8, 62, 31, 109, 23, 231, 120, 220, 222, 102, 28, 199, 220, 180, 42, 35, 243, 63, 45, 161, 155, 19, 169, 230, 163, 248, 141, 109, 44, 240, 189, 44, 136, 53, 89, 148, 250, 225, 95, 244, 231, 24, 39, 51, 185, 230, 54, 23, 48, 104, 84, 188, 99, 164, 206, 230, 16, 21, 38, 141, 199, 9, 77 },
                            PasswordSalt = new byte[] { 39, 241, 206, 221, 77, 230, 37, 254, 141, 35, 127, 234, 59, 30, 60, 191, 186, 46, 222, 64, 121, 239, 211, 122, 28, 124, 122, 150, 206, 39, 1, 242, 250, 19, 183, 56, 133, 99, 178, 101, 233, 60, 70, 223, 43, 33, 77, 50, 230, 141, 230, 69, 157, 125, 70, 142, 5, 43, 44, 183, 246, 29, 109, 54, 184, 220, 108, 230, 215, 191, 222, 229, 81, 202, 190, 178, 15, 216, 153, 165, 85, 55, 241, 254, 228, 149, 223, 158, 55, 170, 220, 134, 139, 104, 51, 228, 148, 162, 141, 74, 177, 187, 171, 76, 155, 13, 33, 226, 83, 131, 91, 165, 35, 41, 146, 145, 17, 29, 251, 72, 68, 192, 43, 17, 160, 130, 136, 188 },
                            Role = "Admin",
                            Username = "Travis"
                        },
                        new
                        {
                            Id = new Guid("730b0202-2cf5-4b95-aa0e-6f7a0c662f12"),
                            FirstName = "Madisyn",
                            LastName = "McCullough",
                            PasswordHash = new byte[] { 187, 8, 62, 31, 109, 23, 231, 120, 220, 222, 102, 28, 199, 220, 180, 42, 35, 243, 63, 45, 161, 155, 19, 169, 230, 163, 248, 141, 109, 44, 240, 189, 44, 136, 53, 89, 148, 250, 225, 95, 244, 231, 24, 39, 51, 185, 230, 54, 23, 48, 104, 84, 188, 99, 164, 206, 230, 16, 21, 38, 141, 199, 9, 77 },
                            PasswordSalt = new byte[] { 39, 241, 206, 221, 77, 230, 37, 254, 141, 35, 127, 234, 59, 30, 60, 191, 186, 46, 222, 64, 121, 239, 211, 122, 28, 124, 122, 150, 206, 39, 1, 242, 250, 19, 183, 56, 133, 99, 178, 101, 233, 60, 70, 223, 43, 33, 77, 50, 230, 141, 230, 69, 157, 125, 70, 142, 5, 43, 44, 183, 246, 29, 109, 54, 184, 220, 108, 230, 215, 191, 222, 229, 81, 202, 190, 178, 15, 216, 153, 165, 85, 55, 241, 254, 228, 149, 223, 158, 55, 170, 220, 134, 139, 104, 51, 228, 148, 162, 141, 74, 177, 187, 171, 76, 155, 13, 33, 226, 83, 131, 91, 165, 35, 41, 146, 145, 17, 29, 251, 72, 68, 192, 43, 17, 160, 130, 136, 188 },
                            Role = "Admin",
                            Username = "Coralie"
                        },
                        new
                        {
                            Id = new Guid("e534fafd-6223-4deb-99e3-c15960a84ac8"),
                            FirstName = "Donna",
                            LastName = "Leannon",
                            PasswordHash = new byte[] { 187, 8, 62, 31, 109, 23, 231, 120, 220, 222, 102, 28, 199, 220, 180, 42, 35, 243, 63, 45, 161, 155, 19, 169, 230, 163, 248, 141, 109, 44, 240, 189, 44, 136, 53, 89, 148, 250, 225, 95, 244, 231, 24, 39, 51, 185, 230, 54, 23, 48, 104, 84, 188, 99, 164, 206, 230, 16, 21, 38, 141, 199, 9, 77 },
                            PasswordSalt = new byte[] { 39, 241, 206, 221, 77, 230, 37, 254, 141, 35, 127, 234, 59, 30, 60, 191, 186, 46, 222, 64, 121, 239, 211, 122, 28, 124, 122, 150, 206, 39, 1, 242, 250, 19, 183, 56, 133, 99, 178, 101, 233, 60, 70, 223, 43, 33, 77, 50, 230, 141, 230, 69, 157, 125, 70, 142, 5, 43, 44, 183, 246, 29, 109, 54, 184, 220, 108, 230, 215, 191, 222, 229, 81, 202, 190, 178, 15, 216, 153, 165, 85, 55, 241, 254, 228, 149, 223, 158, 55, 170, 220, 134, 139, 104, 51, 228, 148, 162, 141, 74, 177, 187, 171, 76, 155, 13, 33, 226, 83, 131, 91, 165, 35, 41, 146, 145, 17, 29, 251, 72, 68, 192, 43, 17, 160, 130, 136, 188 },
                            Role = "Admin",
                            Username = "Yesenia"
                        },
                        new
                        {
                            Id = new Guid("8c677d99-1c3c-4552-9497-2ddc5a826b6e"),
                            FirstName = "Sebastian",
                            LastName = "Schüler",
                            PasswordHash = new byte[] { 187, 8, 62, 31, 109, 23, 231, 120, 220, 222, 102, 28, 199, 220, 180, 42, 35, 243, 63, 45, 161, 155, 19, 169, 230, 163, 248, 141, 109, 44, 240, 189, 44, 136, 53, 89, 148, 250, 225, 95, 244, 231, 24, 39, 51, 185, 230, 54, 23, 48, 104, 84, 188, 99, 164, 206, 230, 16, 21, 38, 141, 199, 9, 77 },
                            PasswordSalt = new byte[] { 39, 241, 206, 221, 77, 230, 37, 254, 141, 35, 127, 234, 59, 30, 60, 191, 186, 46, 222, 64, 121, 239, 211, 122, 28, 124, 122, 150, 206, 39, 1, 242, 250, 19, 183, 56, 133, 99, 178, 101, 233, 60, 70, 223, 43, 33, 77, 50, 230, 141, 230, 69, 157, 125, 70, 142, 5, 43, 44, 183, 246, 29, 109, 54, 184, 220, 108, 230, 215, 191, 222, 229, 81, 202, 190, 178, 15, 216, 153, 165, 85, 55, 241, 254, 228, 149, 223, 158, 55, 170, 220, 134, 139, 104, 51, 228, 148, 162, 141, 74, 177, 187, 171, 76, 155, 13, 33, 226, 83, 131, 91, 165, 35, 41, 146, 145, 17, 29, 251, 72, 68, 192, 43, 17, 160, 130, 136, 188 },
                            Role = "Admin",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WeatherForecastId");

                    b.HasIndex("UserId");

                    b.ToTable("WeatherForecast");
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.HasOne("AngularWeb.Entities.User", "User")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
