// <auto-generated />
using System;
using AngularWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200311160803_Initial_03")]
    partial class Initial_03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularWeb.Entities.Address.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasColumnName("addition")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Addition2")
                        .HasColumnName("addition2")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("AddressCompanyTypeId")
                        .HasColumnName("fk_address_company_type")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressCountryId")
                        .HasColumnName("fk_address_country")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("FAGBinaryId")
                        .HasColumnName("fk_logo")
                        .HasColumnType("bigint");

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnName("fk_parent_address")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnName("postcode")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Street")
                        .HasColumnName("street")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnName("timezone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("VatId")
                        .HasColumnName("vat_id_no")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressCompanyTypeId");

                    b.HasIndex("AddressCountryId");

                    b.HasIndex("FAGBinaryId");

                    b.HasIndex("ParentId");

                    b.ToTable("address_address");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPerson", b =>
                {
                    b.Property<long>("AddressPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .HasColumnName("department")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneOffice")
                        .HasColumnName("phone_office")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhonePrivate")
                        .HasColumnName("phone_private")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("PictureId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressPersonId");

                    b.HasIndex("PictureId");

                    b.ToTable("address_person");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPersonRelation", b =>
                {
                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("AddressPersonId")
                        .HasColumnType("bigint");

                    b.HasKey("AddressId", "AddressPersonId");

                    b.HasIndex("AddressPersonId");

                    b.ToTable("address_person_relation");
                });

            modelBuilder.Entity("AngularWeb.Entities.AddressCompanyType", b =>
                {
                    b.Property<long>("AddressCompanyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("AddressCompanyTypeId");

                    b.ToTable("address_company_type");
                });

            modelBuilder.Entity("AngularWeb.Entities.AddressCountry", b =>
                {
                    b.Property<long>("AddressCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressTextDeliveryScript")
                        .HasColumnName("address_text_delivery_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextDocumentScript")
                        .HasColumnName("address_text_document_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextInvoiceScript")
                        .HasColumnName("address_text_invoice_script")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("AdressType")
                        .HasColumnName("address_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<int>("EconomicArea")
                        .HasColumnName("economic_area")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Iso2cc")
                        .HasColumnName("iso_2cc")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Iso3cc")
                        .HasColumnName("iso_3cc")
                        .HasColumnType("varchar(3)");

                    b.Property<int>("IsoNumerical")
                        .HasColumnName("iso_numerical")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressCountryId");

                    b.ToTable("address_country");
                });

            modelBuilder.Entity("AngularWeb.Entities.Audit_WeatherForecast", b =>
                {
                    b.Property<long>("Audit_WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AuditUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("WeatherForecastId")
                        .HasColumnType("bigint");

                    b.HasKey("Audit_WeatherForecastId");

                    b.ToTable("Audit_WeatherForecast");
                });

            modelBuilder.Entity("AngularWeb.Entities.FAGBinary", b =>
                {
                    b.Property<long>("FAGBinaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Data")
                        .HasColumnName("data")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("FKId")
                        .HasColumnName("fk_id")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasColumnName("file_name")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("FAGBinaryId");

                    b.ToTable("fagBinarys");
                });

            modelBuilder.Entity("AngularWeb.Entities.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Yvette",
                            LastName = "Marquardt",
                            PasswordHash = new byte[] { 28, 165, 120, 217, 243, 135, 40, 212, 14, 9, 181, 133, 71, 113, 65, 247, 91, 133, 156, 237, 46, 157, 96, 118, 121, 239, 21, 61, 249, 161, 20, 159, 130, 234, 187, 175, 12, 66, 40, 224, 117, 162, 31, 92, 90, 6, 101, 115, 245, 211, 251, 20, 180, 176, 193, 30, 13, 200, 185, 215, 58, 61, 131, 106 },
                            PasswordSalt = new byte[] { 135, 55, 108, 115, 36, 128, 86, 239, 253, 162, 139, 103, 195, 52, 250, 39, 196, 254, 66, 24, 148, 12, 158, 128, 230, 103, 88, 108, 111, 59, 82, 128, 114, 230, 75, 167, 56, 70, 27, 240, 170, 93, 171, 43, 201, 47, 119, 204, 140, 24, 221, 1, 83, 12, 200, 243, 87, 70, 14, 97, 55, 24, 41, 68, 13, 250, 200, 190, 32, 245, 47, 68, 181, 163, 241, 173, 141, 141, 77, 9, 253, 53, 63, 217, 247, 114, 116, 42, 132, 156, 133, 126, 119, 127, 10, 219, 21, 54, 1, 134, 34, 120, 68, 195, 235, 123, 252, 50, 144, 104, 3, 202, 29, 249, 193, 175, 159, 232, 65, 57, 92, 176, 120, 13, 255, 32, 190, 5 },
                            Role = "Admin",
                            Username = "Nigel"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Joelle",
                            LastName = "Bergstrom",
                            PasswordHash = new byte[] { 28, 165, 120, 217, 243, 135, 40, 212, 14, 9, 181, 133, 71, 113, 65, 247, 91, 133, 156, 237, 46, 157, 96, 118, 121, 239, 21, 61, 249, 161, 20, 159, 130, 234, 187, 175, 12, 66, 40, 224, 117, 162, 31, 92, 90, 6, 101, 115, 245, 211, 251, 20, 180, 176, 193, 30, 13, 200, 185, 215, 58, 61, 131, 106 },
                            PasswordSalt = new byte[] { 135, 55, 108, 115, 36, 128, 86, 239, 253, 162, 139, 103, 195, 52, 250, 39, 196, 254, 66, 24, 148, 12, 158, 128, 230, 103, 88, 108, 111, 59, 82, 128, 114, 230, 75, 167, 56, 70, 27, 240, 170, 93, 171, 43, 201, 47, 119, 204, 140, 24, 221, 1, 83, 12, 200, 243, 87, 70, 14, 97, 55, 24, 41, 68, 13, 250, 200, 190, 32, 245, 47, 68, 181, 163, 241, 173, 141, 141, 77, 9, 253, 53, 63, 217, 247, 114, 116, 42, 132, 156, 133, 126, 119, 127, 10, 219, 21, 54, 1, 134, 34, 120, 68, 195, 235, 123, 252, 50, 144, 104, 3, 202, 29, 249, 193, 175, 159, 232, 65, 57, 92, 176, 120, 13, 255, 32, 190, 5 },
                            Role = "Admin",
                            Username = "Travis"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Madisyn",
                            LastName = "McCullough",
                            PasswordHash = new byte[] { 28, 165, 120, 217, 243, 135, 40, 212, 14, 9, 181, 133, 71, 113, 65, 247, 91, 133, 156, 237, 46, 157, 96, 118, 121, 239, 21, 61, 249, 161, 20, 159, 130, 234, 187, 175, 12, 66, 40, 224, 117, 162, 31, 92, 90, 6, 101, 115, 245, 211, 251, 20, 180, 176, 193, 30, 13, 200, 185, 215, 58, 61, 131, 106 },
                            PasswordSalt = new byte[] { 135, 55, 108, 115, 36, 128, 86, 239, 253, 162, 139, 103, 195, 52, 250, 39, 196, 254, 66, 24, 148, 12, 158, 128, 230, 103, 88, 108, 111, 59, 82, 128, 114, 230, 75, 167, 56, 70, 27, 240, 170, 93, 171, 43, 201, 47, 119, 204, 140, 24, 221, 1, 83, 12, 200, 243, 87, 70, 14, 97, 55, 24, 41, 68, 13, 250, 200, 190, 32, 245, 47, 68, 181, 163, 241, 173, 141, 141, 77, 9, 253, 53, 63, 217, 247, 114, 116, 42, 132, 156, 133, 126, 119, 127, 10, 219, 21, 54, 1, 134, 34, 120, 68, 195, 235, 123, 252, 50, 144, 104, 3, 202, 29, 249, 193, 175, 159, 232, 65, 57, 92, 176, 120, 13, 255, 32, 190, 5 },
                            Role = "Admin",
                            Username = "Coralie"
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Donna",
                            LastName = "Leannon",
                            PasswordHash = new byte[] { 28, 165, 120, 217, 243, 135, 40, 212, 14, 9, 181, 133, 71, 113, 65, 247, 91, 133, 156, 237, 46, 157, 96, 118, 121, 239, 21, 61, 249, 161, 20, 159, 130, 234, 187, 175, 12, 66, 40, 224, 117, 162, 31, 92, 90, 6, 101, 115, 245, 211, 251, 20, 180, 176, 193, 30, 13, 200, 185, 215, 58, 61, 131, 106 },
                            PasswordSalt = new byte[] { 135, 55, 108, 115, 36, 128, 86, 239, 253, 162, 139, 103, 195, 52, 250, 39, 196, 254, 66, 24, 148, 12, 158, 128, 230, 103, 88, 108, 111, 59, 82, 128, 114, 230, 75, 167, 56, 70, 27, 240, 170, 93, 171, 43, 201, 47, 119, 204, 140, 24, 221, 1, 83, 12, 200, 243, 87, 70, 14, 97, 55, 24, 41, 68, 13, 250, 200, 190, 32, 245, 47, 68, 181, 163, 241, 173, 141, 141, 77, 9, 253, 53, 63, 217, 247, 114, 116, 42, 132, 156, 133, 126, 119, 127, 10, 219, 21, 54, 1, 134, 34, 120, 68, 195, 235, 123, 252, 50, 144, 104, 3, 202, 29, 249, 193, 175, 159, 232, 65, 57, 92, 176, 120, 13, 255, 32, 190, 5 },
                            Role = "Admin",
                            Username = "Yesenia"
                        },
                        new
                        {
                            Id = 5L,
                            FirstName = "Sebastian",
                            LastName = "Schüler",
                            PasswordHash = new byte[] { 28, 165, 120, 217, 243, 135, 40, 212, 14, 9, 181, 133, 71, 113, 65, 247, 91, 133, 156, 237, 46, 157, 96, 118, 121, 239, 21, 61, 249, 161, 20, 159, 130, 234, 187, 175, 12, 66, 40, 224, 117, 162, 31, 92, 90, 6, 101, 115, 245, 211, 251, 20, 180, 176, 193, 30, 13, 200, 185, 215, 58, 61, 131, 106 },
                            PasswordSalt = new byte[] { 135, 55, 108, 115, 36, 128, 86, 239, 253, 162, 139, 103, 195, 52, 250, 39, 196, 254, 66, 24, 148, 12, 158, 128, 230, 103, 88, 108, 111, 59, 82, 128, 114, 230, 75, 167, 56, 70, 27, 240, 170, 93, 171, 43, 201, 47, 119, 204, 140, 24, 221, 1, 83, 12, 200, 243, 87, 70, 14, 97, 55, 24, 41, 68, 13, 250, 200, 190, 32, 245, 47, 68, 181, 163, 241, 173, 141, 141, 77, 9, 253, 53, 63, 217, 247, 114, 116, 42, 132, 156, 133, 126, 119, 127, 10, 219, 21, 54, 1, 134, 34, 120, 68, 195, 235, 123, 252, 50, 144, 104, 3, 202, 29, 249, 193, 175, 159, 232, 65, 57, 92, 176, 120, 13, 255, 32, 190, 5 },
                            Role = "Admin",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.Property<long>("WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasColumnName("summar_y")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("WeatherForecastId");

                    b.HasIndex("UserId");

                    b.ToTable("WeatherForecast");

                    b.HasData(
                        new
                        {
                            WeatherForecastId = 1L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 675, DateTimeKind.Utc).AddTicks(9508),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 12, 22, 9, 19, 16, 169, DateTimeKind.Local).AddTicks(8463),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 676, DateTimeKind.Utc).AddTicks(1950),
                            ModifiedBy = 4L,
                            Summary = "Danish Krone",
                            TemperatureC = 15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 2L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(699),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 11, 14, 15, 40, 57, 6, DateTimeKind.Local).AddTicks(9045),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(755),
                            ModifiedBy = 5L,
                            Summary = "haptic",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 3L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(3103),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 30, 19, 52, 59, 761, DateTimeKind.Local).AddTicks(3468),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(3108),
                            ModifiedBy = 5L,
                            Summary = "orchid",
                            TemperatureC = 5,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 4L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(4761),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 31, 12, 3, 49, 720, DateTimeKind.Local).AddTicks(582),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(4766),
                            ModifiedBy = 1L,
                            Summary = "Practical",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 5L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(6986),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 20, 13, 0, 7, 73, DateTimeKind.Local).AddTicks(3201),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(6990),
                            ModifiedBy = 3L,
                            Summary = "sexy",
                            TemperatureC = -14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 6L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(8636),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 4, 18, 10, 37, 822, DateTimeKind.Local).AddTicks(478),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 677, DateTimeKind.Utc).AddTicks(8640),
                            ModifiedBy = 3L,
                            Summary = "even-keeled",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 7L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 678, DateTimeKind.Utc).AddTicks(247),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 13, 5, 11, 23, 785, DateTimeKind.Local).AddTicks(4596),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 678, DateTimeKind.Utc).AddTicks(252),
                            ModifiedBy = 3L,
                            Summary = "Fully-configurable",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 8L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 678, DateTimeKind.Utc).AddTicks(9994),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 8, 15, 30, 19, 745, DateTimeKind.Local).AddTicks(2680),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 679, DateTimeKind.Utc).AddTicks(3),
                            ModifiedBy = 3L,
                            Summary = "Jewelery",
                            TemperatureC = -15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 9L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 679, DateTimeKind.Utc).AddTicks(4498),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 11, 17, 28, 20, 803, DateTimeKind.Local).AddTicks(5125),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 679, DateTimeKind.Utc).AddTicks(4507),
                            ModifiedBy = 3L,
                            Summary = "Mississippi",
                            TemperatureC = 8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 10L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 679, DateTimeKind.Utc).AddTicks(6866),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 5, 19, 13, 13, 52, 700, DateTimeKind.Local).AddTicks(4419),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 679, DateTimeKind.Utc).AddTicks(6872),
                            ModifiedBy = 5L,
                            Summary = "hard drive",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 11L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(445),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 3, 12, 7, 21, 55, 317, DateTimeKind.Local).AddTicks(6855),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(450),
                            ModifiedBy = 1L,
                            Summary = "Handmade Plastic Towels",
                            TemperatureC = -7,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 12L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2577),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 26, 14, 33, 16, 214, DateTimeKind.Local).AddTicks(234),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2582),
                            ModifiedBy = 1L,
                            Summary = "Assurance",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 13L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2659),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 15, 14, 39, 28, 578, DateTimeKind.Local).AddTicks(6611),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2663),
                            ModifiedBy = 5L,
                            Summary = "mobile",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 14L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2711),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 23, 1, 54, 29, 603, DateTimeKind.Local).AddTicks(612),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2714),
                            ModifiedBy = 3L,
                            Summary = "Customer-focused",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 15L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2754),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 8, 4, 10, 52, 651, DateTimeKind.Local).AddTicks(5026),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(2758),
                            ModifiedBy = 1L,
                            Summary = "national",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 16L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(4201),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 12, 6, 22, 56, 0, 830, DateTimeKind.Local).AddTicks(1071),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(4206),
                            ModifiedBy = 4L,
                            Summary = "Planner",
                            TemperatureC = 14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 17L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(4273),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 18, 12, 54, 49, 218, DateTimeKind.Local).AddTicks(294),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(4277),
                            ModifiedBy = 5L,
                            Summary = "open-source",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 18L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(6043),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 16, 19, 52, 12, 283, DateTimeKind.Local).AddTicks(3463),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(6048),
                            ModifiedBy = 3L,
                            Summary = "niches",
                            TemperatureC = -4,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 19L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(6116),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 10, 12, 7, 42, 59, 440, DateTimeKind.Local).AddTicks(6292),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(6120),
                            ModifiedBy = 4L,
                            Summary = "paradigms",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 20L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(8575),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 29, 18, 55, 24, 162, DateTimeKind.Local).AddTicks(2717),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 680, DateTimeKind.Utc).AddTicks(8580),
                            ModifiedBy = 4L,
                            Summary = "Kids, Electronics & Movies",
                            TemperatureC = 5,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 21L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(505),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 25, 21, 31, 4, 417, DateTimeKind.Local).AddTicks(5008),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(509),
                            ModifiedBy = 5L,
                            Summary = "reinvent",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 22L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(590),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 1, 21, 7, 41, 679, DateTimeKind.Local).AddTicks(8372),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(593),
                            ModifiedBy = 4L,
                            Summary = "Technician",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 23L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(2192),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 5, 3, 40, 14, 506, DateTimeKind.Local).AddTicks(6699),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(2195),
                            ModifiedBy = 1L,
                            Summary = "COM",
                            TemperatureC = -8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 24L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3738),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 27, 23, 36, 17, 848, DateTimeKind.Local).AddTicks(9315),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3742),
                            ModifiedBy = 3L,
                            Summary = "backing up",
                            TemperatureC = -13,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 25L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3814),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 9, 22, 51, 20, 650, DateTimeKind.Local).AddTicks(9769),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3817),
                            ModifiedBy = 3L,
                            Summary = "Delaware",
                            TemperatureC = -1,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 26L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3886),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 22, 9, 35, 48, 11, DateTimeKind.Local).AddTicks(531),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3889),
                            ModifiedBy = 5L,
                            Summary = "Practical Metal Hat",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 27L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3931),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 7, 19, 11, 45, 875, DateTimeKind.Local).AddTicks(4507),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(3934),
                            ModifiedBy = 3L,
                            Summary = "1080p",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 28L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(4117),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 8, 23, 17, 38, 29, 40, DateTimeKind.Local).AddTicks(4445),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(4120),
                            ModifiedBy = 1L,
                            Summary = "Self-enabling",
                            TemperatureC = 10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 29L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(6036),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 14, 21, 4, 36, 836, DateTimeKind.Local).AddTicks(5624),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(6040),
                            ModifiedBy = 3L,
                            Summary = "Credit Card Account",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 30L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(6120),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 4, 12, 14, 56, 16, 595, DateTimeKind.Local).AddTicks(1794),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(6125),
                            ModifiedBy = 1L,
                            Summary = "connecting",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 31L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(6356),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 1, 23, 59, 3, 947, DateTimeKind.Local).AddTicks(4343),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(6366),
                            ModifiedBy = 1L,
                            Summary = "Incredible Wooden Shoes",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 32L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(7782),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 16, 20, 36, 37, 204, DateTimeKind.Local).AddTicks(3633),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 681, DateTimeKind.Utc).AddTicks(7793),
                            ModifiedBy = 4L,
                            Summary = "Rustic Steel Pants",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 33L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(784),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 24, 5, 8, 11, 529, DateTimeKind.Local).AddTicks(6394),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(796),
                            ModifiedBy = 5L,
                            Summary = "Principal",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 34L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(945),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 25, 6, 42, 34, 846, DateTimeKind.Local).AddTicks(7212),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(953),
                            ModifiedBy = 2L,
                            Summary = "e-markets",
                            TemperatureC = -11,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 35L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1062),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 13, 18, 1, 21, 624, DateTimeKind.Local).AddTicks(4800),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1066),
                            ModifiedBy = 2L,
                            Summary = "efficient",
                            TemperatureC = -1,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 36L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1173),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 7, 23, 34, 22, 139, DateTimeKind.Local).AddTicks(7821),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1178),
                            ModifiedBy = 1L,
                            Summary = "Mobility",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 37L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1277),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 10, 11, 10, 34, 37, 876, DateTimeKind.Local).AddTicks(2109),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1287),
                            ModifiedBy = 3L,
                            Summary = "cyan",
                            TemperatureC = -4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 38L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1463),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 12, 3, 49, 33, 333, DateTimeKind.Local).AddTicks(4136),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1467),
                            ModifiedBy = 4L,
                            Summary = "Intelligent Concrete Shoes",
                            TemperatureC = 14,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 39L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1535),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 21, 14, 50, 17, 428, DateTimeKind.Local).AddTicks(4882),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1538),
                            ModifiedBy = 4L,
                            Summary = "calculating",
                            TemperatureC = 9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 40L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1579),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 11, 16, 40, 49, 513, DateTimeKind.Local).AddTicks(3440),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(1582),
                            ModifiedBy = 2L,
                            Summary = "auxiliary",
                            TemperatureC = -10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 41L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2323),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 1, 49, 37, 159, DateTimeKind.Local).AddTicks(1716),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2327),
                            ModifiedBy = 4L,
                            Summary = "Metal",
                            TemperatureC = -1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 42L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2657),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 7, 17, 6, 29, 1, 770, DateTimeKind.Local).AddTicks(8771),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2661),
                            ModifiedBy = 5L,
                            Summary = "Baby, Beauty & Games",
                            TemperatureC = -4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 43L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2881),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 19, 8, 57, 6, 237, DateTimeKind.Local).AddTicks(2987),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2884),
                            ModifiedBy = 4L,
                            Summary = "Incredible Frozen Cheese",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 44L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2946),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 6, 6, 35, 52, 242, DateTimeKind.Local).AddTicks(1867),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(2949),
                            ModifiedBy = 5L,
                            Summary = "Tunisian Dinar",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 45L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4479),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 1, 6, 2, 31, 14, 283, DateTimeKind.Local).AddTicks(9246),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4483),
                            ModifiedBy = 2L,
                            Summary = "bypass",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 46L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4550),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 31, 7, 40, 48, 858, DateTimeKind.Local).AddTicks(3889),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4553),
                            ModifiedBy = 3L,
                            Summary = "networks",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 47L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4620),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 15, 1, 35, 39, 941, DateTimeKind.Local).AddTicks(2121),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4623),
                            ModifiedBy = 4L,
                            Summary = "fuchsia",
                            TemperatureC = -3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 48L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4671),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 21, 13, 26, 17, 30, DateTimeKind.Local).AddTicks(9933),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(4674),
                            ModifiedBy = 5L,
                            Summary = "Brazilian Real",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 49L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6140),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 27, 8, 10, 3, 921, DateTimeKind.Local).AddTicks(4069),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6144),
                            ModifiedBy = 2L,
                            Summary = "Trafficway",
                            TemperatureC = 15,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 50L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6213),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 18, 12, 42, 34, 868, DateTimeKind.Local).AddTicks(3824),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6216),
                            ModifiedBy = 2L,
                            Summary = "Direct",
                            TemperatureC = 3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 51L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6257),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 20, 23, 2, 13, 629, DateTimeKind.Local).AddTicks(2471),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6260),
                            ModifiedBy = 5L,
                            Summary = "Implementation",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 52L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6296),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 5, 15, 7, 18, 1, DateTimeKind.Local).AddTicks(999),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6299),
                            ModifiedBy = 4L,
                            Summary = "Brand",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 53L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6333),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 3, 19, 3, 36, 0, 627, DateTimeKind.Local).AddTicks(3875),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6336),
                            ModifiedBy = 5L,
                            Summary = "Identity",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 54L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6372),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 24, 18, 21, 23, 493, DateTimeKind.Local).AddTicks(4894),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6375),
                            ModifiedBy = 5L,
                            Summary = "Internal",
                            TemperatureC = 11,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 55L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6421),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 18, 11, 31, 19, 474, DateTimeKind.Local).AddTicks(8140),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6423),
                            ModifiedBy = 4L,
                            Summary = "Guarani",
                            TemperatureC = -6,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 56L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6459),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 30, 10, 10, 58, 880, DateTimeKind.Local).AddTicks(413),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6462),
                            ModifiedBy = 3L,
                            Summary = "Central",
                            TemperatureC = 8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 57L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6555),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 19, 2, 46, 18, 901, DateTimeKind.Local).AddTicks(5135),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6565),
                            ModifiedBy = 3L,
                            Summary = "online",
                            TemperatureC = 4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 58L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6745),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 3, 11, 15, 10, 3, 894, DateTimeKind.Local).AddTicks(4668),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6752),
                            ModifiedBy = 4L,
                            Summary = "index",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 59L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6870),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 2, 18, 54, 45, 451, DateTimeKind.Local).AddTicks(153),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6876),
                            ModifiedBy = 1L,
                            Summary = "scale",
                            TemperatureC = -15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 60L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6979),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 16, 14, 52, 17, 144, DateTimeKind.Local).AddTicks(9377),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(6983),
                            ModifiedBy = 2L,
                            Summary = "supply-chains",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 61L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7207),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 21, 19, 2, 54, 323, DateTimeKind.Local).AddTicks(7148),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7216),
                            ModifiedBy = 2L,
                            Summary = "SMS",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 62L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7316),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 22, 20, 10, 12, 593, DateTimeKind.Local).AddTicks(7572),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7323),
                            ModifiedBy = 2L,
                            Summary = "cultivate",
                            TemperatureC = -12,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 63L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7415),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 21, 7, 41, 17, 26, DateTimeKind.Local).AddTicks(1332),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7422),
                            ModifiedBy = 4L,
                            Summary = "Advanced",
                            TemperatureC = 14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 64L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7516),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 6, 30, 6, 45, 57, 631, DateTimeKind.Local).AddTicks(8350),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7526),
                            ModifiedBy = 2L,
                            Summary = "input",
                            TemperatureC = 1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 65L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7704),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 11, 8, 22, 50, 623, DateTimeKind.Local).AddTicks(3800),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7711),
                            ModifiedBy = 4L,
                            Summary = "Movies & Clothing",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 66L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7812),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 27, 22, 27, 12, 410, DateTimeKind.Local).AddTicks(8233),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7821),
                            ModifiedBy = 5L,
                            Summary = "Lead",
                            TemperatureC = 4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 67L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7922),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 16, 4, 44, 44, 439, DateTimeKind.Local).AddTicks(1761),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(7931),
                            ModifiedBy = 3L,
                            Summary = "Agent",
                            TemperatureC = -12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 68L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8032),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 29, 17, 18, 27, 446, DateTimeKind.Local).AddTicks(9036),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8041),
                            ModifiedBy = 5L,
                            Summary = "real-time",
                            TemperatureC = 2,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 69L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8139),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 17, 34, 9, 38, DateTimeKind.Local).AddTicks(8698),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8143),
                            ModifiedBy = 3L,
                            Summary = "Corporate",
                            TemperatureC = -14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 70L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8284),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 9, 24, 5, 13, 1, 21, DateTimeKind.Local).AddTicks(1591),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8290),
                            ModifiedBy = 5L,
                            Summary = "Small Cotton Car",
                            TemperatureC = -4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 71L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8383),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 16, 13, 45, 30, 405, DateTimeKind.Local).AddTicks(1917),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8390),
                            ModifiedBy = 4L,
                            Summary = "connecting",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 72L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8487),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 10, 1, 23, 20, 7, 130, DateTimeKind.Local).AddTicks(9487),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8494),
                            ModifiedBy = 5L,
                            Summary = "Gorgeous",
                            TemperatureC = -2,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 73L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8586),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 1, 6, 40, 46, 858, DateTimeKind.Local).AddTicks(2099),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8593),
                            ModifiedBy = 5L,
                            Summary = "scale",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 74L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8686),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 5, 31, 2, 32, 45, 391, DateTimeKind.Local).AddTicks(2747),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8695),
                            ModifiedBy = 5L,
                            Summary = "olive",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 75L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8786),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 4, 6, 0, 8, 39, 619, DateTimeKind.Local).AddTicks(2259),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8794),
                            ModifiedBy = 1L,
                            Summary = "Pre-emptive",
                            TemperatureC = -3,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 76L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8893),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 16, 2, 45, 10, 429, DateTimeKind.Local).AddTicks(4190),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 682, DateTimeKind.Utc).AddTicks(8899),
                            ModifiedBy = 4L,
                            Summary = "Officer",
                            TemperatureC = 7,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 77L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(221),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 10, 16, 6, 3, 880, DateTimeKind.Local).AddTicks(6147),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(231),
                            ModifiedBy = 2L,
                            Summary = "Square",
                            TemperatureC = 7,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 78L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(363),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 12, 29, 9, 31, 55, 813, DateTimeKind.Local).AddTicks(7169),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(370),
                            ModifiedBy = 1L,
                            Summary = "wireless",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 79L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(469),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 23, 25, 50, 856, DateTimeKind.Local).AddTicks(8223),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(478),
                            ModifiedBy = 1L,
                            Summary = "SMS",
                            TemperatureC = 4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 80L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(730),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 23, 11, 17, 25, 902, DateTimeKind.Local).AddTicks(2943),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(737),
                            ModifiedBy = 5L,
                            Summary = "Investment Account",
                            TemperatureC = 12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 81L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(843),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 7, 1, 42, 38, 267, DateTimeKind.Local).AddTicks(7068),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(848),
                            ModifiedBy = 5L,
                            Summary = "Maine",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 82L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(946),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 29, 16, 55, 49, 317, DateTimeKind.Local).AddTicks(6065),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(955),
                            ModifiedBy = 2L,
                            Summary = "AI",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 83L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(1053),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 27, 10, 45, 4, 687, DateTimeKind.Local).AddTicks(9506),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(1059),
                            ModifiedBy = 1L,
                            Summary = "open-source",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 84L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(2931),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 29, 14, 39, 2, 313, DateTimeKind.Local).AddTicks(3508),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(2936),
                            ModifiedBy = 5L,
                            Summary = "Berkshire",
                            TemperatureC = -11,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 85L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4549),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 9, 17, 8, 11, 397, DateTimeKind.Local).AddTicks(2214),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4554),
                            ModifiedBy = 4L,
                            Summary = "conglomeration",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 86L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4782),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 28, 17, 21, 58, 425, DateTimeKind.Local).AddTicks(9820),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4785),
                            ModifiedBy = 5L,
                            Summary = "Walks",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 87L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4832),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 6, 17, 55, 15, 250, DateTimeKind.Local).AddTicks(3764),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4835),
                            ModifiedBy = 5L,
                            Summary = "world-class",
                            TemperatureC = 15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 88L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4878),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 22, 9, 1, 1, 700, DateTimeKind.Local).AddTicks(7904),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4881),
                            ModifiedBy = 2L,
                            Summary = "Triple-buffered",
                            TemperatureC = 10,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 89L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4927),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 14, 19, 55, 54, 79, DateTimeKind.Local).AddTicks(6429),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4930),
                            ModifiedBy = 5L,
                            Summary = "District",
                            TemperatureC = -13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 90L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4989),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 28, 12, 8, 37, 961, DateTimeKind.Local).AddTicks(6190),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(4992),
                            ModifiedBy = 2L,
                            Summary = "Small Cotton Keyboard",
                            TemperatureC = 2,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 91L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5033),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 6, 5, 0, 9, 56, 460, DateTimeKind.Local).AddTicks(1114),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5036),
                            ModifiedBy = 5L,
                            Summary = "driver",
                            TemperatureC = -10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 92L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5073),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 25, 3, 29, 58, 663, DateTimeKind.Local).AddTicks(8596),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5076),
                            ModifiedBy = 2L,
                            Summary = "parse",
                            TemperatureC = 10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 93L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5124),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 31, 12, 9, 49, 726, DateTimeKind.Local).AddTicks(6828),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5127),
                            ModifiedBy = 3L,
                            Summary = "Latvian Lats",
                            TemperatureC = -6,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 94L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5165),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 16, 14, 22, 50, 705, DateTimeKind.Local).AddTicks(1275),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5168),
                            ModifiedBy = 4L,
                            Summary = "Centralized",
                            TemperatureC = 11,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 95L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5208),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 6, 34, 44, 661, DateTimeKind.Local).AddTicks(8846),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5211),
                            ModifiedBy = 4L,
                            Summary = "web-enabled",
                            TemperatureC = -12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 96L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5251),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 25, 16, 15, 2, 85, DateTimeKind.Local).AddTicks(2039),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(5254),
                            ModifiedBy = 4L,
                            Summary = "Credit Card Account",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 97L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(6772),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 9, 21, 28, 40, 550, DateTimeKind.Local).AddTicks(3791),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(6776),
                            ModifiedBy = 4L,
                            Summary = "Cayman Islands",
                            TemperatureC = 13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 98L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(8276),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 8, 12, 19, 20, 27, 18, DateTimeKind.Local).AddTicks(4077),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(8280),
                            ModifiedBy = 2L,
                            Summary = "withdrawal",
                            TemperatureC = 8,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 99L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(8416),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 23, 7, 36, 44, 249, DateTimeKind.Local).AddTicks(5954),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(8419),
                            ModifiedBy = 4L,
                            Summary = "Response",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 100L,
                            Created = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(8480),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 6, 14, 15, 4, 495, DateTimeKind.Local).AddTicks(7966),
                            Modified = new DateTime(2020, 3, 11, 16, 8, 2, 683, DateTimeKind.Utc).AddTicks(8483),
                            ModifiedBy = 5L,
                            Summary = "Tasty Rubber Keyboard",
                            TemperatureC = 0,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.Address", b =>
                {
                    b.HasOne("AngularWeb.Entities.AddressCompanyType", "AddressCompanyType")
                        .WithMany()
                        .HasForeignKey("AddressCompanyTypeId");

                    b.HasOne("AngularWeb.Entities.AddressCountry", "AddressCountry")
                        .WithMany()
                        .HasForeignKey("AddressCountryId");

                    b.HasOne("AngularWeb.Entities.FAGBinary", "Logo")
                        .WithMany()
                        .HasForeignKey("FAGBinaryId");

                    b.HasOne("AngularWeb.Entities.Address.Address", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPerson", b =>
                {
                    b.HasOne("AngularWeb.Entities.FAGBinary", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPersonRelation", b =>
                {
                    b.HasOne("AngularWeb.Entities.Address.Address", "Address")
                        .WithMany("AddressPersonRelations")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AngularWeb.Entities.Address.AddressPerson", "AddressPerson")
                        .WithMany("AddressPersonRelations")
                        .HasForeignKey("AddressPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.HasOne("AngularWeb.Entities.User.User", "User")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
