// <auto-generated />
using System;
using AngularWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularWeb.Entities.Address.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasColumnName("addition")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Addition2")
                        .HasColumnName("addition2")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("AddressCompanyTypeId")
                        .HasColumnName("fk_address_company_type")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressCountryId")
                        .HasColumnName("fk_address_country")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("FAGBinaryId")
                        .HasColumnName("fk_logo")
                        .HasColumnType("bigint");

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnName("fk_parent_address")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnName("postcode")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Street")
                        .HasColumnName("street")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnName("timezone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("VatId")
                        .HasColumnName("vat_id_no")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressCompanyTypeId");

                    b.HasIndex("AddressCountryId");

                    b.HasIndex("FAGBinaryId");

                    b.HasIndex("ParentId");

                    b.ToTable("address_address");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPerson", b =>
                {
                    b.Property<long>("AddressPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .HasColumnName("department")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneOffice")
                        .HasColumnName("phone_office")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhonePrivate")
                        .HasColumnName("phone_private")
                        .HasColumnType("varchar(max)");

                    b.Property<long?>("PictureId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressPersonId");

                    b.HasIndex("PictureId");

                    b.ToTable("address_person");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPersonRelation", b =>
                {
                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("AddressPersonId")
                        .HasColumnType("bigint");

                    b.Property<long>("AddressPersonRelationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("AddressId", "AddressPersonId");

                    b.HasIndex("AddressPersonId");

                    b.ToTable("address_person_relation");
                });

            modelBuilder.Entity("AngularWeb.Entities.AddressCompanyType", b =>
                {
                    b.Property<long>("AddressCompanyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("AddressCompanyTypeId");

                    b.ToTable("address_company_type");
                });

            modelBuilder.Entity("AngularWeb.Entities.AddressCountry", b =>
                {
                    b.Property<long>("AddressCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressTextDeliveryScript")
                        .HasColumnName("address_text_delivery_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextDocumentScript")
                        .HasColumnName("address_text_document_script")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AddressTextInvoiceScript")
                        .HasColumnName("address_text_invoice_script")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("AdressType")
                        .HasColumnName("address_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<int>("EconomicArea")
                        .HasColumnName("economic_area")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Iso2cc")
                        .HasColumnName("iso_2cc")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Iso3cc")
                        .HasColumnName("iso_3cc")
                        .HasColumnType("varchar(3)");

                    b.Property<int>("IsoNumerical")
                        .HasColumnName("iso_numerical")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.HasKey("AddressCountryId");

                    b.ToTable("address_country");
                });

            modelBuilder.Entity("AngularWeb.Entities.Audit_WeatherForecast", b =>
                {
                    b.Property<long>("Audit_WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("AuditUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("WeatherForecastId")
                        .HasColumnType("bigint");

                    b.HasKey("Audit_WeatherForecastId");

                    b.ToTable("Audit_WeatherForecast");
                });

            modelBuilder.Entity("AngularWeb.Entities.FAGBinary", b =>
                {
                    b.Property<long>("FAGBinaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Data")
                        .HasColumnName("data")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("FKId")
                        .HasColumnName("fk_id")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasColumnName("file_name")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("FAGBinaryId");

                    b.ToTable("fagBinarys");
                });

            modelBuilder.Entity("AngularWeb.Entities.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Yvette",
                            LastName = "Marquardt",
                            PasswordHash = new byte[] { 251, 127, 70, 143, 47, 41, 252, 246, 241, 29, 244, 33, 27, 222, 141, 107, 56, 229, 15, 227, 69, 209, 210, 213, 223, 207, 186, 105, 173, 233, 157, 38, 51, 178, 215, 234, 12, 149, 114, 219, 90, 214, 176, 121, 144, 175, 16, 197, 131, 199, 190, 226, 197, 250, 139, 182, 153, 185, 141, 63, 129, 128, 164, 207 },
                            PasswordSalt = new byte[] { 22, 75, 71, 84, 177, 46, 81, 54, 177, 149, 169, 221, 109, 14, 205, 245, 2, 84, 48, 19, 43, 255, 8, 193, 78, 255, 77, 252, 90, 172, 119, 31, 15, 98, 215, 94, 34, 210, 27, 212, 255, 134, 178, 70, 25, 255, 169, 152, 232, 224, 91, 240, 204, 193, 211, 187, 119, 66, 43, 182, 204, 255, 124, 223, 167, 203, 213, 235, 241, 216, 16, 216, 177, 52, 110, 138, 220, 87, 222, 156, 115, 66, 157, 134, 238, 175, 125, 237, 161, 216, 195, 99, 92, 151, 74, 75, 20, 232, 158, 246, 212, 223, 200, 70, 249, 210, 225, 42, 249, 217, 43, 49, 204, 48, 255, 255, 206, 149, 221, 194, 117, 20, 205, 15, 237, 42, 174, 36 },
                            Role = "Admin",
                            Username = "Nigel"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Joelle",
                            LastName = "Bergstrom",
                            PasswordHash = new byte[] { 251, 127, 70, 143, 47, 41, 252, 246, 241, 29, 244, 33, 27, 222, 141, 107, 56, 229, 15, 227, 69, 209, 210, 213, 223, 207, 186, 105, 173, 233, 157, 38, 51, 178, 215, 234, 12, 149, 114, 219, 90, 214, 176, 121, 144, 175, 16, 197, 131, 199, 190, 226, 197, 250, 139, 182, 153, 185, 141, 63, 129, 128, 164, 207 },
                            PasswordSalt = new byte[] { 22, 75, 71, 84, 177, 46, 81, 54, 177, 149, 169, 221, 109, 14, 205, 245, 2, 84, 48, 19, 43, 255, 8, 193, 78, 255, 77, 252, 90, 172, 119, 31, 15, 98, 215, 94, 34, 210, 27, 212, 255, 134, 178, 70, 25, 255, 169, 152, 232, 224, 91, 240, 204, 193, 211, 187, 119, 66, 43, 182, 204, 255, 124, 223, 167, 203, 213, 235, 241, 216, 16, 216, 177, 52, 110, 138, 220, 87, 222, 156, 115, 66, 157, 134, 238, 175, 125, 237, 161, 216, 195, 99, 92, 151, 74, 75, 20, 232, 158, 246, 212, 223, 200, 70, 249, 210, 225, 42, 249, 217, 43, 49, 204, 48, 255, 255, 206, 149, 221, 194, 117, 20, 205, 15, 237, 42, 174, 36 },
                            Role = "Admin",
                            Username = "Travis"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Madisyn",
                            LastName = "McCullough",
                            PasswordHash = new byte[] { 251, 127, 70, 143, 47, 41, 252, 246, 241, 29, 244, 33, 27, 222, 141, 107, 56, 229, 15, 227, 69, 209, 210, 213, 223, 207, 186, 105, 173, 233, 157, 38, 51, 178, 215, 234, 12, 149, 114, 219, 90, 214, 176, 121, 144, 175, 16, 197, 131, 199, 190, 226, 197, 250, 139, 182, 153, 185, 141, 63, 129, 128, 164, 207 },
                            PasswordSalt = new byte[] { 22, 75, 71, 84, 177, 46, 81, 54, 177, 149, 169, 221, 109, 14, 205, 245, 2, 84, 48, 19, 43, 255, 8, 193, 78, 255, 77, 252, 90, 172, 119, 31, 15, 98, 215, 94, 34, 210, 27, 212, 255, 134, 178, 70, 25, 255, 169, 152, 232, 224, 91, 240, 204, 193, 211, 187, 119, 66, 43, 182, 204, 255, 124, 223, 167, 203, 213, 235, 241, 216, 16, 216, 177, 52, 110, 138, 220, 87, 222, 156, 115, 66, 157, 134, 238, 175, 125, 237, 161, 216, 195, 99, 92, 151, 74, 75, 20, 232, 158, 246, 212, 223, 200, 70, 249, 210, 225, 42, 249, 217, 43, 49, 204, 48, 255, 255, 206, 149, 221, 194, 117, 20, 205, 15, 237, 42, 174, 36 },
                            Role = "Admin",
                            Username = "Coralie"
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Donna",
                            LastName = "Leannon",
                            PasswordHash = new byte[] { 251, 127, 70, 143, 47, 41, 252, 246, 241, 29, 244, 33, 27, 222, 141, 107, 56, 229, 15, 227, 69, 209, 210, 213, 223, 207, 186, 105, 173, 233, 157, 38, 51, 178, 215, 234, 12, 149, 114, 219, 90, 214, 176, 121, 144, 175, 16, 197, 131, 199, 190, 226, 197, 250, 139, 182, 153, 185, 141, 63, 129, 128, 164, 207 },
                            PasswordSalt = new byte[] { 22, 75, 71, 84, 177, 46, 81, 54, 177, 149, 169, 221, 109, 14, 205, 245, 2, 84, 48, 19, 43, 255, 8, 193, 78, 255, 77, 252, 90, 172, 119, 31, 15, 98, 215, 94, 34, 210, 27, 212, 255, 134, 178, 70, 25, 255, 169, 152, 232, 224, 91, 240, 204, 193, 211, 187, 119, 66, 43, 182, 204, 255, 124, 223, 167, 203, 213, 235, 241, 216, 16, 216, 177, 52, 110, 138, 220, 87, 222, 156, 115, 66, 157, 134, 238, 175, 125, 237, 161, 216, 195, 99, 92, 151, 74, 75, 20, 232, 158, 246, 212, 223, 200, 70, 249, 210, 225, 42, 249, 217, 43, 49, 204, 48, 255, 255, 206, 149, 221, 194, 117, 20, 205, 15, 237, 42, 174, 36 },
                            Role = "Admin",
                            Username = "Yesenia"
                        },
                        new
                        {
                            Id = 5L,
                            FirstName = "Sebastian",
                            LastName = "Schüler",
                            PasswordHash = new byte[] { 251, 127, 70, 143, 47, 41, 252, 246, 241, 29, 244, 33, 27, 222, 141, 107, 56, 229, 15, 227, 69, 209, 210, 213, 223, 207, 186, 105, 173, 233, 157, 38, 51, 178, 215, 234, 12, 149, 114, 219, 90, 214, 176, 121, 144, 175, 16, 197, 131, 199, 190, 226, 197, 250, 139, 182, 153, 185, 141, 63, 129, 128, 164, 207 },
                            PasswordSalt = new byte[] { 22, 75, 71, 84, 177, 46, 81, 54, 177, 149, 169, 221, 109, 14, 205, 245, 2, 84, 48, 19, 43, 255, 8, 193, 78, 255, 77, 252, 90, 172, 119, 31, 15, 98, 215, 94, 34, 210, 27, 212, 255, 134, 178, 70, 25, 255, 169, 152, 232, 224, 91, 240, 204, 193, 211, 187, 119, 66, 43, 182, 204, 255, 124, 223, 167, 203, 213, 235, 241, 216, 16, 216, 177, 52, 110, 138, 220, 87, 222, 156, 115, 66, 157, 134, 238, 175, 125, 237, 161, 216, 195, 99, 92, 151, 74, 75, 20, 232, 158, 246, 212, 223, 200, 70, 249, 210, 225, 42, 249, 217, 43, 49, 204, 48, 255, 255, 206, 149, 221, 194, 117, 20, 205, 15, 237, 42, 174, 36 },
                            Role = "Admin",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.Property<long>("WeatherForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnName("info")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InfoRtf")
                        .HasColumnName("info_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasColumnName("summar_y")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("WeatherForecastId");

                    b.HasIndex("UserId");

                    b.ToTable("WeatherForecast");

                    b.HasData(
                        new
                        {
                            WeatherForecastId = 1L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 987, DateTimeKind.Utc).AddTicks(1936),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 12, 22, 9, 22, 41, 480, DateTimeKind.Local).AddTicks(3297),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 987, DateTimeKind.Utc).AddTicks(5010),
                            ModifiedBy = 4L,
                            Summary = "Danish Krone",
                            TemperatureC = 15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 2L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 988, DateTimeKind.Utc).AddTicks(6004),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 11, 14, 15, 44, 22, 318, DateTimeKind.Local).AddTicks(4313),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 988, DateTimeKind.Utc).AddTicks(6086),
                            ModifiedBy = 5L,
                            Summary = "haptic",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 3L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 988, DateTimeKind.Utc).AddTicks(9229),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 30, 19, 56, 25, 72, DateTimeKind.Local).AddTicks(9577),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 988, DateTimeKind.Utc).AddTicks(9236),
                            ModifiedBy = 5L,
                            Summary = "orchid",
                            TemperatureC = 5,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 4L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(1835),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 31, 12, 7, 15, 31, DateTimeKind.Local).AddTicks(7657),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(1845),
                            ModifiedBy = 1L,
                            Summary = "Practical",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 5L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(5137),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 20, 13, 3, 32, 385, DateTimeKind.Local).AddTicks(1345),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(5142),
                            ModifiedBy = 3L,
                            Summary = "sexy",
                            TemperatureC = -14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 6L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(6896),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 4, 18, 14, 3, 133, DateTimeKind.Local).AddTicks(8730),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(6900),
                            ModifiedBy = 3L,
                            Summary = "even-keeled",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 7L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(8596),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 13, 5, 14, 49, 97, DateTimeKind.Local).AddTicks(2942),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 989, DateTimeKind.Utc).AddTicks(8601),
                            ModifiedBy = 3L,
                            Summary = "Fully-configurable",
                            TemperatureC = -3,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 8L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 990, DateTimeKind.Utc).AddTicks(5611),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 8, 15, 33, 45, 56, DateTimeKind.Local).AddTicks(8339),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 990, DateTimeKind.Utc).AddTicks(5616),
                            ModifiedBy = 3L,
                            Summary = "Jewelery",
                            TemperatureC = -15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 9L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 990, DateTimeKind.Utc).AddTicks(8104),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 11, 17, 31, 46, 114, DateTimeKind.Local).AddTicks(8772),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 990, DateTimeKind.Utc).AddTicks(8109),
                            ModifiedBy = 3L,
                            Summary = "Mississippi",
                            TemperatureC = 8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 10L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(185),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 5, 19, 13, 17, 18, 11, DateTimeKind.Local).AddTicks(7734),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(191),
                            ModifiedBy = 5L,
                            Summary = "hard drive",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 11L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(4126),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 3, 12, 7, 25, 20, 629, DateTimeKind.Local).AddTicks(530),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(4132),
                            ModifiedBy = 1L,
                            Summary = "Handmade Plastic Towels",
                            TemperatureC = -7,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 12L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6368),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 26, 14, 36, 41, 525, DateTimeKind.Local).AddTicks(4025),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6373),
                            ModifiedBy = 1L,
                            Summary = "Assurance",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 13L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6452),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 15, 14, 42, 53, 890, DateTimeKind.Local).AddTicks(406),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6455),
                            ModifiedBy = 5L,
                            Summary = "mobile",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 14L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6503),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 23, 1, 57, 54, 914, DateTimeKind.Local).AddTicks(4403),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6508),
                            ModifiedBy = 3L,
                            Summary = "Customer-focused",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 15L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6633),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 8, 4, 14, 17, 962, DateTimeKind.Local).AddTicks(8867),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(6639),
                            ModifiedBy = 1L,
                            Summary = "national",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 16L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(8933),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 12, 6, 22, 59, 26, 141, DateTimeKind.Local).AddTicks(5780),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 991, DateTimeKind.Utc).AddTicks(8941),
                            ModifiedBy = 4L,
                            Summary = "Planner",
                            TemperatureC = 14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 17L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(795),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 18, 12, 58, 14, 529, DateTimeKind.Local).AddTicks(6745),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(805),
                            ModifiedBy = 5L,
                            Summary = "open-source",
                            TemperatureC = -9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 18L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(4816),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 16, 19, 55, 37, 595, DateTimeKind.Local).AddTicks(2206),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(4824),
                            ModifiedBy = 3L,
                            Summary = "niches",
                            TemperatureC = -4,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 19L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(4948),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 10, 12, 7, 46, 24, 752, DateTimeKind.Local).AddTicks(5111),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(4953),
                            ModifiedBy = 4L,
                            Summary = "paradigms",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 20L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(9648),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 29, 18, 58, 49, 474, DateTimeKind.Local).AddTicks(3751),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 992, DateTimeKind.Utc).AddTicks(9657),
                            ModifiedBy = 4L,
                            Summary = "Kids, Electronics & Movies",
                            TemperatureC = 5,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 21L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(2727),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 25, 21, 34, 29, 729, DateTimeKind.Local).AddTicks(7210),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(2734),
                            ModifiedBy = 5L,
                            Summary = "reinvent",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 22L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(2866),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 1, 21, 11, 6, 992, DateTimeKind.Local).AddTicks(640),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(2872),
                            ModifiedBy = 4L,
                            Summary = "Technician",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 23L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(5149),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 5, 3, 43, 39, 818, DateTimeKind.Local).AddTicks(9640),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(5156),
                            ModifiedBy = 1L,
                            Summary = "COM",
                            TemperatureC = -8,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 24L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7337),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 27, 23, 39, 43, 161, DateTimeKind.Local).AddTicks(2893),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7344),
                            ModifiedBy = 3L,
                            Summary = "backing up",
                            TemperatureC = -13,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 25L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7456),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 9, 22, 54, 45, 963, DateTimeKind.Local).AddTicks(3402),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7462),
                            ModifiedBy = 3L,
                            Summary = "Delaware",
                            TemperatureC = -1,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 26L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7577),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 22, 9, 39, 13, 323, DateTimeKind.Local).AddTicks(4215),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7583),
                            ModifiedBy = 5L,
                            Summary = "Practical Metal Hat",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 27L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7650),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 7, 19, 15, 11, 187, DateTimeKind.Local).AddTicks(8219),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7655),
                            ModifiedBy = 3L,
                            Summary = "1080p",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 28L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7972),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 8, 23, 17, 41, 54, 352, DateTimeKind.Local).AddTicks(8276),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 993, DateTimeKind.Utc).AddTicks(7984),
                            ModifiedBy = 1L,
                            Summary = "Self-enabling",
                            TemperatureC = 10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 29L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(311),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 14, 21, 8, 2, 148, DateTimeKind.Local).AddTicks(9885),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(317),
                            ModifiedBy = 3L,
                            Summary = "Credit Card Account",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 30L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(399),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 4, 12, 14, 59, 41, 907, DateTimeKind.Local).AddTicks(6078),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(402),
                            ModifiedBy = 1L,
                            Summary = "connecting",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 31L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(472),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 2, 0, 2, 29, 259, DateTimeKind.Local).AddTicks(8510),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(475),
                            ModifiedBy = 1L,
                            Summary = "Incredible Wooden Shoes",
                            TemperatureC = -8,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 32L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(1257),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 7, 16, 20, 40, 2, 516, DateTimeKind.Local).AddTicks(7136),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(1262),
                            ModifiedBy = 4L,
                            Summary = "Rustic Steel Pants",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 33L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3493),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 3, 24, 5, 11, 36, 841, DateTimeKind.Local).AddTicks(9095),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3503),
                            ModifiedBy = 5L,
                            Summary = "Principal",
                            TemperatureC = 3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 34L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3683),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 25, 6, 46, 0, 158, DateTimeKind.Local).AddTicks(9943),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3691),
                            ModifiedBy = 2L,
                            Summary = "e-markets",
                            TemperatureC = -11,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 35L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3807),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 13, 18, 4, 46, 936, DateTimeKind.Local).AddTicks(7544),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3816),
                            ModifiedBy = 2L,
                            Summary = "efficient",
                            TemperatureC = -1,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 36L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3938),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 7, 23, 37, 47, 452, DateTimeKind.Local).AddTicks(585),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(3946),
                            ModifiedBy = 1L,
                            Summary = "Mobility",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 37L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4058),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 10, 11, 10, 38, 3, 188, DateTimeKind.Local).AddTicks(4886),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4065),
                            ModifiedBy = 3L,
                            Summary = "cyan",
                            TemperatureC = -4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 38L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4272),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 12, 3, 52, 58, 645, DateTimeKind.Local).AddTicks(6943),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4276),
                            ModifiedBy = 4L,
                            Summary = "Intelligent Concrete Shoes",
                            TemperatureC = 14,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 39L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4346),
                            CreatedBy = 4L,
                            Date = new DateTime(2021, 2, 21, 14, 53, 42, 740, DateTimeKind.Local).AddTicks(7693),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4349),
                            ModifiedBy = 4L,
                            Summary = "calculating",
                            TemperatureC = 9,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 40L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4393),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 11, 16, 44, 14, 825, DateTimeKind.Local).AddTicks(6253),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(4396),
                            ModifiedBy = 2L,
                            Summary = "auxiliary",
                            TemperatureC = -10,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 41L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5204),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 1, 53, 2, 471, DateTimeKind.Local).AddTicks(4594),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5208),
                            ModifiedBy = 4L,
                            Summary = "Metal",
                            TemperatureC = -1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 42L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5619),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 7, 17, 6, 32, 27, 83, DateTimeKind.Local).AddTicks(1729),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5623),
                            ModifiedBy = 5L,
                            Summary = "Baby, Beauty & Games",
                            TemperatureC = -4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 43L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5770),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 19, 9, 0, 31, 549, DateTimeKind.Local).AddTicks(5878),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5773),
                            ModifiedBy = 4L,
                            Summary = "Incredible Frozen Cheese",
                            TemperatureC = 15,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 44L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5837),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 6, 6, 39, 17, 554, DateTimeKind.Local).AddTicks(4759),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(5840),
                            ModifiedBy = 5L,
                            Summary = "Tunisian Dinar",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 45L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7513),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 1, 6, 2, 34, 39, 596, DateTimeKind.Local).AddTicks(2276),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7518),
                            ModifiedBy = 2L,
                            Summary = "bypass",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 46L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7589),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 31, 7, 44, 14, 170, DateTimeKind.Local).AddTicks(6928),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7592),
                            ModifiedBy = 3L,
                            Summary = "networks",
                            TemperatureC = 13,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 47L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7633),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 4, 15, 1, 39, 5, 253, DateTimeKind.Local).AddTicks(5135),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7636),
                            ModifiedBy = 4L,
                            Summary = "fuchsia",
                            TemperatureC = -3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 48L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7686),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 21, 13, 29, 42, 343, DateTimeKind.Local).AddTicks(2949),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(7689),
                            ModifiedBy = 5L,
                            Summary = "Brazilian Real",
                            TemperatureC = -6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 49L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9756),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 2, 27, 8, 13, 29, 233, DateTimeKind.Local).AddTicks(7670),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9762),
                            ModifiedBy = 2L,
                            Summary = "Trafficway",
                            TemperatureC = 15,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 50L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9852),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 8, 18, 12, 46, 0, 180, DateTimeKind.Local).AddTicks(7461),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9855),
                            ModifiedBy = 2L,
                            Summary = "Direct",
                            TemperatureC = 3,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 51L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9905),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 20, 23, 5, 38, 941, DateTimeKind.Local).AddTicks(6119),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9908),
                            ModifiedBy = 5L,
                            Summary = "Implementation",
                            TemperatureC = 0,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 52L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9948),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 9, 5, 15, 10, 43, 313, DateTimeKind.Local).AddTicks(4652),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9951),
                            ModifiedBy = 4L,
                            Summary = "Brand",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 53L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9990),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 3, 19, 3, 39, 25, 939, DateTimeKind.Local).AddTicks(7531),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 994, DateTimeKind.Utc).AddTicks(9993),
                            ModifiedBy = 5L,
                            Summary = "Identity",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 54L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(33),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 24, 18, 24, 48, 805, DateTimeKind.Local).AddTicks(8554),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(36),
                            ModifiedBy = 5L,
                            Summary = "Internal",
                            TemperatureC = 11,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 55L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(90),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 3, 18, 11, 34, 44, 787, DateTimeKind.Local).AddTicks(1809),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(93),
                            ModifiedBy = 4L,
                            Summary = "Guarani",
                            TemperatureC = -6,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 56L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(132),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 30, 10, 14, 24, 192, DateTimeKind.Local).AddTicks(4086),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(135),
                            ModifiedBy = 3L,
                            Summary = "Central",
                            TemperatureC = 8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 57L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(176),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 6, 19, 2, 49, 44, 213, DateTimeKind.Local).AddTicks(8794),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(179),
                            ModifiedBy = 3L,
                            Summary = "online",
                            TemperatureC = 4,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 58L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(216),
                            CreatedBy = 3L,
                            Date = new DateTime(2021, 3, 11, 15, 13, 29, 206, DateTimeKind.Local).AddTicks(8188),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(220),
                            ModifiedBy = 4L,
                            Summary = "index",
                            TemperatureC = 14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 59L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 2, 18, 58, 10, 763, DateTimeKind.Local).AddTicks(3568),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(263),
                            ModifiedBy = 1L,
                            Summary = "scale",
                            TemperatureC = -15,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 60L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(301),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 16, 14, 55, 42, 457, DateTimeKind.Local).AddTicks(2719),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(304),
                            ModifiedBy = 2L,
                            Summary = "supply-chains",
                            TemperatureC = -8,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 61L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(414),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 21, 19, 6, 19, 636, DateTimeKind.Local).AddTicks(375),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(418),
                            ModifiedBy = 2L,
                            Summary = "SMS",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 62L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(459),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 8, 22, 20, 13, 37, 906, DateTimeKind.Local).AddTicks(734),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(462),
                            ModifiedBy = 2L,
                            Summary = "cultivate",
                            TemperatureC = -12,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 63L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(501),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 21, 7, 44, 42, 338, DateTimeKind.Local).AddTicks(4437),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(504),
                            ModifiedBy = 4L,
                            Summary = "Advanced",
                            TemperatureC = 14,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 64L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(541),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 6, 30, 6, 49, 22, 944, DateTimeKind.Local).AddTicks(1393),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(544),
                            ModifiedBy = 2L,
                            Summary = "input",
                            TemperatureC = 1,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 65L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(634),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 6, 11, 8, 26, 15, 935, DateTimeKind.Local).AddTicks(6748),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(637),
                            ModifiedBy = 4L,
                            Summary = "Movies & Clothing",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 66L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(678),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 8, 27, 22, 30, 37, 723, DateTimeKind.Local).AddTicks(1116),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(681),
                            ModifiedBy = 5L,
                            Summary = "Lead",
                            TemperatureC = 4,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 67L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(721),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 16, 4, 48, 9, 751, DateTimeKind.Local).AddTicks(4577),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(724),
                            ModifiedBy = 3L,
                            Summary = "Agent",
                            TemperatureC = -12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 68L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(765),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 29, 17, 21, 52, 759, DateTimeKind.Local).AddTicks(1785),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(768),
                            ModifiedBy = 5L,
                            Summary = "real-time",
                            TemperatureC = 2,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 69L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(805),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 1, 7, 17, 37, 34, 351, DateTimeKind.Local).AddTicks(1387),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(808),
                            ModifiedBy = 3L,
                            Summary = "Corporate",
                            TemperatureC = -14,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 70L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(867),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 9, 24, 5, 16, 26, 333, DateTimeKind.Local).AddTicks(4194),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(870),
                            ModifiedBy = 5L,
                            Summary = "Small Cotton Car",
                            TemperatureC = -4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 71L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(908),
                            CreatedBy = 2L,
                            Date = new DateTime(2021, 2, 16, 13, 48, 55, 717, DateTimeKind.Local).AddTicks(4461),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(911),
                            ModifiedBy = 4L,
                            Summary = "connecting",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 72L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(949),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 10, 1, 23, 23, 32, 443, DateTimeKind.Local).AddTicks(1966),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(952),
                            ModifiedBy = 5L,
                            Summary = "Gorgeous",
                            TemperatureC = -2,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 73L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(988),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 12, 1, 6, 44, 12, 170, DateTimeKind.Local).AddTicks(4521),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(991),
                            ModifiedBy = 5L,
                            Summary = "scale",
                            TemperatureC = 6,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 74L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1028),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 5, 31, 2, 36, 10, 703, DateTimeKind.Local).AddTicks(5106),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1032),
                            ModifiedBy = 5L,
                            Summary = "olive",
                            TemperatureC = 4,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 75L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1069),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 4, 6, 0, 12, 4, 931, DateTimeKind.Local).AddTicks(4560),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1073),
                            ModifiedBy = 1L,
                            Summary = "Pre-emptive",
                            TemperatureC = -3,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 76L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1110),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 7, 16, 2, 48, 35, 741, DateTimeKind.Local).AddTicks(6426),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1113),
                            ModifiedBy = 4L,
                            Summary = "Officer",
                            TemperatureC = 7,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 77L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1877),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 10, 16, 9, 29, 192, DateTimeKind.Local).AddTicks(7827),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1881),
                            ModifiedBy = 2L,
                            Summary = "Square",
                            TemperatureC = 7,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 78L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1944),
                            CreatedBy = 5L,
                            Date = new DateTime(2020, 12, 29, 9, 35, 21, 125, DateTimeKind.Local).AddTicks(8770),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1947),
                            ModifiedBy = 1L,
                            Summary = "wireless",
                            TemperatureC = -14,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 79L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1986),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 23, 29, 16, 168, DateTimeKind.Local).AddTicks(9758),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(1990),
                            ModifiedBy = 1L,
                            Summary = "SMS",
                            TemperatureC = 4,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 80L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2100),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 23, 11, 20, 51, 214, DateTimeKind.Local).AddTicks(4334),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2103),
                            ModifiedBy = 5L,
                            Summary = "Investment Account",
                            TemperatureC = 12,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 81L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2143),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 7, 1, 46, 3, 579, DateTimeKind.Local).AddTicks(8390),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2146),
                            ModifiedBy = 5L,
                            Summary = "Maine",
                            TemperatureC = -3,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 82L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2184),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 5, 29, 16, 59, 14, 629, DateTimeKind.Local).AddTicks(7319),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2187),
                            ModifiedBy = 2L,
                            Summary = "AI",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 83L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2225),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 27, 10, 48, 30, 0, DateTimeKind.Local).AddTicks(699),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(2228),
                            ModifiedBy = 1L,
                            Summary = "open-source",
                            TemperatureC = 12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 84L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(3800),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 7, 29, 14, 42, 27, 625, DateTimeKind.Local).AddTicks(4384),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(3805),
                            ModifiedBy = 5L,
                            Summary = "Berkshire",
                            TemperatureC = -11,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 85L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5486),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 5, 9, 17, 11, 36, 709, DateTimeKind.Local).AddTicks(3177),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5490),
                            ModifiedBy = 4L,
                            Summary = "conglomeration",
                            TemperatureC = 10,
                            UserId = 2L
                        },
                        new
                        {
                            WeatherForecastId = 86L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5561),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 9, 28, 17, 25, 23, 738, DateTimeKind.Local).AddTicks(752),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5564),
                            ModifiedBy = 5L,
                            Summary = "Walks",
                            TemperatureC = 8,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 87L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5605),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 10, 6, 17, 58, 40, 562, DateTimeKind.Local).AddTicks(4539),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5609),
                            ModifiedBy = 5L,
                            Summary = "world-class",
                            TemperatureC = 15,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 88L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5648),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 22, 9, 4, 27, 12, DateTimeKind.Local).AddTicks(8674),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5651),
                            ModifiedBy = 2L,
                            Summary = "Triple-buffered",
                            TemperatureC = 10,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 89L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5694),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 11, 14, 19, 59, 19, 391, DateTimeKind.Local).AddTicks(7197),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5697),
                            ModifiedBy = 5L,
                            Summary = "District",
                            TemperatureC = -13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 90L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5756),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 28, 12, 12, 3, 273, DateTimeKind.Local).AddTicks(6958),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5760),
                            ModifiedBy = 2L,
                            Summary = "Small Cotton Keyboard",
                            TemperatureC = 2,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 91L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5801),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 6, 5, 0, 13, 21, 772, DateTimeKind.Local).AddTicks(1882),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5804),
                            ModifiedBy = 5L,
                            Summary = "driver",
                            TemperatureC = -10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 92L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5842),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 1, 25, 3, 33, 23, 975, DateTimeKind.Local).AddTicks(9366),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5846),
                            ModifiedBy = 2L,
                            Summary = "parse",
                            TemperatureC = 10,
                            UserId = 1L
                        },
                        new
                        {
                            WeatherForecastId = 93L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5895),
                            CreatedBy = 3L,
                            Date = new DateTime(2020, 7, 31, 12, 13, 15, 38, DateTimeKind.Local).AddTicks(7600),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5899),
                            ModifiedBy = 3L,
                            Summary = "Latvian Lats",
                            TemperatureC = -6,
                            UserId = 4L
                        },
                        new
                        {
                            WeatherForecastId = 94L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5938),
                            CreatedBy = 1L,
                            Date = new DateTime(2021, 2, 16, 14, 26, 16, 17, DateTimeKind.Local).AddTicks(2048),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5941),
                            ModifiedBy = 4L,
                            Summary = "Centralized",
                            TemperatureC = 11,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 95L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5979),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 1, 25, 6, 38, 9, 973, DateTimeKind.Local).AddTicks(9617),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(5982),
                            ModifiedBy = 4L,
                            Summary = "web-enabled",
                            TemperatureC = -12,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 96L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(6022),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 4, 25, 16, 18, 27, 397, DateTimeKind.Local).AddTicks(2811),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(6025),
                            ModifiedBy = 4L,
                            Summary = "Credit Card Account",
                            TemperatureC = -12,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 97L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(7589),
                            CreatedBy = 5L,
                            Date = new DateTime(2021, 2, 9, 21, 32, 5, 862, DateTimeKind.Local).AddTicks(4607),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 995, DateTimeKind.Utc).AddTicks(7593),
                            ModifiedBy = 4L,
                            Summary = "Cayman Islands",
                            TemperatureC = 13,
                            UserId = 3L
                        },
                        new
                        {
                            WeatherForecastId = 98L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 996, DateTimeKind.Utc).AddTicks(145),
                            CreatedBy = 4L,
                            Date = new DateTime(2020, 8, 12, 19, 23, 52, 330, DateTimeKind.Local).AddTicks(5893),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 996, DateTimeKind.Utc).AddTicks(157),
                            ModifiedBy = 2L,
                            Summary = "withdrawal",
                            TemperatureC = 8,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 99L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 996, DateTimeKind.Utc).AddTicks(313),
                            CreatedBy = 2L,
                            Date = new DateTime(2020, 11, 23, 7, 40, 9, 561, DateTimeKind.Local).AddTicks(7841),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 996, DateTimeKind.Utc).AddTicks(318),
                            ModifiedBy = 4L,
                            Summary = "Response",
                            TemperatureC = 0,
                            UserId = 5L
                        },
                        new
                        {
                            WeatherForecastId = 100L,
                            Created = new DateTime(2020, 3, 11, 16, 11, 27, 996, DateTimeKind.Utc).AddTicks(439),
                            CreatedBy = 1L,
                            Date = new DateTime(2020, 10, 6, 14, 18, 29, 807, DateTimeKind.Local).AddTicks(9915),
                            Modified = new DateTime(2020, 3, 11, 16, 11, 27, 996, DateTimeKind.Utc).AddTicks(443),
                            ModifiedBy = 5L,
                            Summary = "Tasty Rubber Keyboard",
                            TemperatureC = 0,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.Address", b =>
                {
                    b.HasOne("AngularWeb.Entities.AddressCompanyType", "AddressCompanyType")
                        .WithMany()
                        .HasForeignKey("AddressCompanyTypeId");

                    b.HasOne("AngularWeb.Entities.AddressCountry", "AddressCountry")
                        .WithMany()
                        .HasForeignKey("AddressCountryId");

                    b.HasOne("AngularWeb.Entities.FAGBinary", "Logo")
                        .WithMany()
                        .HasForeignKey("FAGBinaryId");

                    b.HasOne("AngularWeb.Entities.Address.Address", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPerson", b =>
                {
                    b.HasOne("AngularWeb.Entities.FAGBinary", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");
                });

            modelBuilder.Entity("AngularWeb.Entities.Address.AddressPersonRelation", b =>
                {
                    b.HasOne("AngularWeb.Entities.Address.Address", "Address")
                        .WithMany("AddressPersonRelations")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AngularWeb.Entities.Address.AddressPerson", "AddressPerson")
                        .WithMany("AddressPersonRelations")
                        .HasForeignKey("AddressPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AngularWeb.Entities.WeatherForecast", b =>
                {
                    b.HasOne("AngularWeb.Entities.User.User", "User")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
