// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Bogus;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;

namespace AngularWeb.Entities
{
    [Table("weather_forecast")]
    public class WeatherForecast :  BaseEntity
    {
        public long WeatherForecastId { get; set; }
        public DateTime Date { get; set; }
       
        public int TemperatureC { get; set; }
        [Column("summar_y", TypeName = "varchar(100)")]
        public string Summary { get; set; }
        [JsonIgnore]
        public long UserId { get; set; }
        public User User { get; set; }
}

    public class WeatherForecastConfiguration : IEntityTypeConfiguration<WeatherForecast>
    {
        public void Configure(EntityTypeBuilder<WeatherForecast> builder)
        {

            int index = 1;
            var TestWeatherForecast = new Faker<WeatherForecast>()
            .RuleFor(item => item.WeatherForecastId, faker => index++)
            .RuleFor(item => item.TemperatureC, faker => faker.Random.Number(-15, 15))
            .RuleFor(item => item.Summary, faker => faker.Random.Word())
            .RuleFor(item => item.Date, faker => faker.Date.Future())
            .RuleFor(item => item.UserId, faker => faker.Random.Number(1, 5))
            .RuleFor(item => item.Created, faker => DateTime.UtcNow)
            .RuleFor(item => item.Modified, faker => DateTime.UtcNow)
            .RuleFor(item => item.CreatedBy, faker => faker.Random.Number(1, 5))
            .RuleFor(item => item.ModifiedBy, faker => faker.Random.Number(1, 5));

            builder.ToTable("WeatherForecast");
            builder.HasData(TestWeatherForecast.Generate(100).ToArray());
        }
    }


    public class Audit_WeatherForecast
    {
        public long Audit_WeatherForecastId { get; set; }
        public long WeatherForecastId { get; set; }
        public DateTime Date { get; set; }
        public int TemperatureC { get; set; }
        public string Summary { get; set; }

        public long AuditUser { get; set; }
        public DateTime AuditDate { get; set; }
        public string AuditAction { get; set; } // "Insert", "Update" or "Delete"

    }

    public class Audit_WeatherForecastConfiguration : IEntityTypeConfiguration<Audit_WeatherForecast>
    {
        public void Configure(EntityTypeBuilder<Audit_WeatherForecast> builder)
        {
            builder.ToTable("Audit_WeatherForecast");
        }
    }
}